use anyhow::{bail, Context, Result};
use std::path::Path;
use std::process::Command;

/// Verify an sBPF project: check source hash, regenerate if stale, run lake build.
///
/// Returns Ok(()) if proofs are valid, Err if stale/broken.
pub fn verify(asm_source: &Path, proofs_dir: &Path) -> Result<()> {
    let source = std::fs::read_to_string(asm_source)
        .with_context(|| format!("reading {}", asm_source.display()))?;

    let current_hash = crate::asm2lean::source_hash(&source);

    // Find the generated Lean module (any file with source-hash comment)
    let generated_file = find_generated_module(proofs_dir)?;
    let generated_content = std::fs::read_to_string(&generated_file)
        .with_context(|| format!("reading {}", generated_file.display()))?;

    let embedded_hash = crate::asm2lean::extract_source_hash(&generated_content);

    let stale = match &embedded_hash {
        Some(h) => h != &current_hash,
        None => {
            eprintln!(
                "Warning: {} has no source hash (generated before v1.5). Regenerating.",
                generated_file.display()
            );
            true
        }
    };

    if stale {
        eprintln!(
            "Source hash mismatch — regenerating {} from {}",
            generated_file.display(),
            asm_source.display()
        );
        // Derive namespace from the generated file's stem
        let namespace = generated_file
            .file_stem()
            .map(|s| s.to_string_lossy().to_string())
            .unwrap_or_else(|| "Program".to_string());
        crate::asm2lean::asm2lean(asm_source, &generated_file, Some(&namespace))?;
    } else {
        eprintln!("Source hash matches (sha256:{}...)", &current_hash[..12]);
    }

    // Run lake build
    eprintln!("Running lake build in {}", proofs_dir.display());
    let status = Command::new("lake")
        .arg("build")
        .current_dir(proofs_dir)
        .status()
        .with_context(|| "failed to run `lake build`")?;

    if !status.success() {
        bail!("lake build failed — proofs are broken");
    }

    eprintln!("Verification passed.");
    Ok(())
}

/// Find the asm2lean-generated Lean file in a proofs directory.
/// Looks for files containing "Auto-generated by qedgen asm2lean".
fn find_generated_module(proofs_dir: &Path) -> Result<std::path::PathBuf> {
    for entry in std::fs::read_dir(proofs_dir)
        .with_context(|| format!("reading directory {}", proofs_dir.display()))?
    {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("lean") {
            if let Ok(content) = std::fs::read_to_string(&path) {
                if content.contains("Auto-generated by qedgen asm2lean") {
                    return Ok(path);
                }
            }
        }
    }
    bail!(
        "No asm2lean-generated .lean file found in {}. Run `qedgen init --asm` first.",
        proofs_dir.display()
    );
}
