#[allow(unused_imports)]
use super::*;

pub(super) fn render_sbpf(spec: &crate::check::ParsedSpec) -> String {
    let mut out = String::new();

    // E.g. spec Slippage → "SlippageProg".
    let prog_module = format!("{}Prog", spec.program_name);

    out.push_str(&format!(
        "-- Generated by qedgen from {}.qedspec\n\
         -- Source of truth: the .qedspec file. Regenerate with:\n\
         --   qedgen codegen --lean --spec <spec>.qedspec --lean-output <this-file>\n\n",
        spec.program_name.to_lowercase()
    ));

    out.push_str("import QEDGen\n");
    out.push_str(&format!("import {}\n\n", prog_module));

    out.push_str("open SVM.SBPF\n");
    out.push_str("open SVM.SBPF.Memory\n\n");

    // ── Global constants ─────────────────────────────────────────────────
    if !spec.constants.is_empty() {
        out.push_str("-- Global constants (from prog module, not re-declared):\n");
        for (name, val) in &spec.constants {
            let clean_val = val.replace('_', "");
            out.push_str(&format!("--   {} = {}\n", name, clean_val));
        }
        out.push('\n');
    }

    // ── Pubkey constants ───────────────────────────────────────────────────
    if !spec.pubkeys.is_empty() {
        out.push_str("-- Known pubkey constants (from prog module, not re-declared):\n");
        for pk in &spec.pubkeys {
            for (i, chunk) in pk.chunks.iter().enumerate() {
                let clean = chunk.replace('_', "");
                out.push_str(&format!(
                    "--   PUBKEY_{}_CHUNK_{} = {}\n",
                    pk.name.to_ascii_uppercase(),
                    i,
                    clean
                ));
            }
        }
        out.push('\n');
    }

    // ── Per-instruction blocks ───────────────────────────────────────────
    for instr in &spec.instructions {
        let ns = &instr.name;
        out.push_str(&format!("namespace {}\n\n", ns));

        // Instruction-level constants
        if !instr.constants.is_empty() {
            out.push_str("-- Instruction-level constants\n");
            for (name, val) in &instr.constants {
                let clean_val = val.replace('_', "");
                out.push_str(&format!("abbrev {} : Nat := {}\n", name, clean_val));
            }
            out.push('\n');
        }

        // Error constants — use instruction-level if present, else global
        let errors = if !instr.errors.is_empty() {
            &instr.errors
        } else {
            &spec.valued_errors
        };
        if !errors.is_empty() {
            out.push_str("-- Error constants\n");
            for err in errors {
                if let Some(val) = err.value {
                    let lean_name = error_to_lean_name(&err.name);
                    out.push_str(&format!("abbrev {} : Nat := {}\n", lean_name, val));
                }
            }
            out.push('\n');
        }

        // Offset constants (from input_layout + insn_layout)
        let all_offsets: Vec<(&str, &str, i64, bool)> = instr
            .input_layout
            .iter()
            .map(|f| (f.name.as_str(), f.field_type.as_str(), f.offset, false))
            .chain(
                instr
                    .insn_layout
                    .iter()
                    .map(|f| (f.name.as_str(), f.field_type.as_str(), f.offset, true)),
            )
            .collect();

        if !all_offsets.is_empty() {
            out.push_str("-- Offset constants\n");
            for (name, _ftype, offset, _is_insn) in &all_offsets {
                let lean_name = offset_to_lean_name(name);
                out.push_str(&format!("abbrev {} : Int := {}\n", lean_name, offset));
            }
            out.push('\n');

            // ea_* lemmas
            out.push_str("-- Effective address lemmas\n");
            for (name, _ftype, offset, _is_insn) in &all_offsets {
                let lean_name = offset_to_lean_name(name);
                let rhs = if *offset == 0 {
                    "b".to_string()
                } else if *offset > 0 {
                    format!("b + {}", offset)
                } else {
                    format!("b - {}", offset.unsigned_abs())
                };
                out.push_str(&format!(
                    "@[simp] theorem ea_{} (b : Nat) : effectiveAddr b {} = {} := by\n  \
                     unfold effectiveAddr {}; omega\n\n",
                    lean_name, lean_name, rhs, lean_name
                ));
            }
        }

        let entry = instr.entry.unwrap_or(0);
        let has_insn_reg = !instr.insn_layout.is_empty();
        // qedsvm's initState takes a RegionTable; accesses outside it trap
        // to ERR_ACCESS_VIOLATION. Obligations bind `rt` and carry one
        // coverage hypothesis per derived read (`rt.containsRange ... = true`,
        // the SVM.SBPF.Patterns idiom) — with a symbolic inputAddr the check
        // cannot reduce by decidability, only by hypothesis rewrite.
        let init_expr = if has_insn_reg {
            format!("initState2 inputAddr insnAddr mem rt {}", entry)
        } else {
            "initState inputAddr mem rt".to_string()
        };

        if !instr.guards.is_empty() {
            out.push_str("-- Guard theorem stubs\n");
            out.push_str(
                "-- Hypotheses derived from checks + layout. Fill proofs with wp_exec.\n\n",
            );

            let mut accumulated_after: Vec<(String, String)> = Vec::new();

            for guard in &instr.guards {
                let error_lean = error_to_lean_name(&guard.error);
                let hyps = derive_guard_hypotheses(guard, &all_offsets, instr, spec);

                if let Some(ref doc) = guard.doc {
                    out.push_str(&format!("/-- {} -/\n", doc.trim()));
                }

                out.push_str(&format!("theorem {}\n", guard.name));

                if has_insn_reg {
                    out.push_str("    (inputAddr insnAddr : Nat) (mem : Mem) (rt : RegionTable)\n");
                } else {
                    out.push_str("    (inputAddr : Nat) (mem : Mem) (rt : RegionTable)\n");
                }

                for (var_decl, _) in &accumulated_after {
                    out.push_str(&format!("    {}\n", var_decl));
                }

                for hyp in &hyps.bindings {
                    out.push_str(&format!("    {}\n", hyp));
                }

                let fuel_str = match guard.fuel {
                    Some(f) => f.to_string(),
                    None => "FUEL".to_string(),
                };
                out.push_str(&format!(
                    "    :\n    (executeFn {}.progAt ({}) {}).exitCode\n      \
                     = some {} := sorry\n\n",
                    prog_module, init_expr, fuel_str, error_lean
                ));

                if let Some(ref after_hyps) = hyps.after {
                    for ah in after_hyps {
                        accumulated_after.push((ah.clone(), String::new()));
                    }
                }
            }

            out.push_str(
                "-- Completeness structure: fill all fields to prove every guard is covered\n",
            );
            out.push_str("structure Spec (progAt : Nat \u{2192} Option Insn) where\n");

            let mut acc_after_for_spec: Vec<String> = Vec::new();
            for guard in &instr.guards {
                let error_lean = error_to_lean_name(&guard.error);
                let hyps = derive_guard_hypotheses(guard, &all_offsets, instr, spec);

                let mut binders = Vec::new();
                if has_insn_reg {
                    binders.push("(inputAddr insnAddr : Nat)".to_string());
                } else {
                    binders.push("(inputAddr : Nat)".to_string());
                }
                binders.push("(mem : Mem)".to_string());
                binders.push("(rt : RegionTable)".to_string());
                for ah in &acc_after_for_spec {
                    binders.push(prefix_unused_binder(ah));
                }
                for b in &hyps.bindings {
                    if !b.starts_with("--") {
                        binders.push(prefix_unused_binder(b));
                    }
                }

                let binder_str = binders.join(" ");
                let fuel_str = match guard.fuel {
                    Some(f) => f.to_string(),
                    None => "FUEL".to_string(),
                };
                out.push_str(&format!(
                    "  {} :\n    \u{2200} {},\n    \
                     (executeFn progAt ({}) {}).exitCode = some {}\n",
                    guard.name, binder_str, init_expr, fuel_str, error_lean
                ));

                if let Some(ref after_hyps) = hyps.after {
                    for ah in after_hyps {
                        acc_after_for_spec.push(ah.clone());
                    }
                }
            }
            out.push('\n');
        }

        if !instr.properties.is_empty() {
            out.push_str("-- Property theorem stubs\n\n");
            for prop in &instr.properties {
                if let Some(ref doc) = prop.doc {
                    out.push_str(&format!("/-- {} -/\n", doc.trim()));
                }
                out.push_str(&format!("theorem {} : True := trivial\n\n", prop.name));
            }
        }

        out.push_str(&format!("end {}\n\n", ns));
    }

    out
}

/// Hypotheses derived from a guard's checks expression and the layout.
pub(super) struct DerivedHypotheses {
    /// Lean hypothesis binders (e.g., "(disc : Nat)", "(h_disc_val : readU8 mem insnAddr = disc)")
    bindings: Vec<String>,
    /// After-hypotheses for the next guard (what becomes true if this guard passes)
    after: Option<Vec<String>>,
}

/// Region-coverage hypothesis for one derived read: under qedsvm semantics
/// the `ldx` at this address traps unless `rt` maps it, and with a symbolic
/// base address the check only closes by hypothesis rewrite.
pub(super) fn region_hyp(var_name: &str, read_fn: &str, addr_expr: &str) -> String {
    let width = match read_fn {
        "readU8" => 1,
        "readU16" => 2,
        "readU32" => 4,
        _ => 8,
    };
    format!(
        "(h_rt_{} : rt.containsRange {} {} = true)",
        var_name, addr_expr, width
    )
}

/// Derive guard hypotheses from checks expression + input/insn layout.
pub(super) fn derive_guard_hypotheses(
    guard: &crate::check::ParsedGuard,
    all_offsets: &[(&str, &str, i64, bool)],
    _instr: &crate::check::ParsedInstruction,
    _spec: &crate::check::ParsedSpec,
) -> DerivedHypotheses {
    // Use raw checks (preserves constant names) for Lean output
    let checks_str = guard.checks_raw.as_ref().or(guard.checks.as_ref());
    let Some(checks) = checks_str else {
        // No checks expression — generate minimal placeholder
        return DerivedHypotheses {
            bindings: vec!["-- TODO: add guard-specific hypotheses".to_string()],
            after: None,
        };
    };

    // Parse checks expression: "field == CONST" / "field >= CONST".
    let parts: Vec<&str> = checks.split_whitespace().collect();

    if parts.len() == 3 {
        let field_name = parts[0];
        let op = parts[1];
        let const_name = parts[2];

        if let Some((_, ftype, offset, is_insn)) = all_offsets
            .iter()
            .find(|(name, _, _, _)| *name == field_name)
        {
            let read_fn = match *ftype {
                "U8" => "readU8",
                "U64" => "readU64",
                "Pubkey" => "readU64", // Pubkey fields are 4-chunk comparisons
                _ => "readU64",
            };

            let base_reg = if *is_insn { "insnAddr" } else { "inputAddr" };
            let addr_expr = if *offset == 0 {
                base_reg.to_string()
            } else if *offset > 0 {
                format!("({} + {})", base_reg, offset)
            } else {
                format!("({} - {})", base_reg, offset.unsigned_abs())
            };

            let var_name = field_name_to_var(field_name);

            // const_name may itself be a layout field (field-vs-field comparison).
            let rhs_is_field = all_offsets
                .iter()
                .find(|(name, _, _, _)| *name == const_name);

            // Field RHS gets its own variable + read hypothesis.
            let (rhs_var, rhs_bindings) = if let Some((_, rtype, roffset, r_is_insn)) = rhs_is_field
            {
                let rhs_read = match *rtype {
                    "U8" => "readU8",
                    _ => "readU64",
                };
                let rhs_base = if *r_is_insn { "insnAddr" } else { "inputAddr" };
                let rhs_addr = if *roffset == 0 {
                    rhs_base.to_string()
                } else if *roffset > 0 {
                    format!("({} + {})", rhs_base, roffset)
                } else {
                    format!("({} - {})", rhs_base, roffset.unsigned_abs())
                };
                let rhs_vname = field_name_to_var(const_name);
                let binds = vec![
                    format!("({} : Nat)", rhs_vname),
                    format!(
                        "(h_{}_val : {} mem {} = {})",
                        rhs_vname, rhs_read, rhs_addr, rhs_vname
                    ),
                    region_hyp(&rhs_vname, rhs_read, &rhs_addr),
                ];
                (rhs_vname, binds)
            } else {
                // RHS is a constant name (preserve as-is from checks_raw)
                (const_name.to_string(), vec![])
            };

            match op {
                "==" => {
                    let mut bindings = vec![
                        format!("({} : Nat)", var_name),
                        format!(
                            "(h_{}_val : {} mem {} = {})",
                            var_name, read_fn, addr_expr, var_name
                        ),
                        region_hyp(&var_name, read_fn, &addr_expr),
                    ];
                    bindings.extend(rhs_bindings.clone());
                    bindings.push(format!(
                        "(h_{}_ne : {} \u{2260} {})",
                        var_name, var_name, rhs_var
                    ));
                    // Later guards re-execute through this access: carry the
                    // pass-condition AND its region coverage forward.
                    let after = Some(vec![
                        format!(
                            "(h_{} : {} mem {} = {})",
                            var_name, read_fn, addr_expr, rhs_var
                        ),
                        region_hyp(&var_name, read_fn, &addr_expr),
                    ]);
                    DerivedHypotheses { bindings, after }
                }
                ">=" => {
                    let mut bindings = vec![
                        format!("({} : Nat)", var_name),
                        format!(
                            "(h_{}_val : {} mem {} = {})",
                            var_name, read_fn, addr_expr, var_name
                        ),
                        region_hyp(&var_name, read_fn, &addr_expr),
                    ];
                    bindings.extend(rhs_bindings.clone());
                    bindings.push(format!("(h_{}_lt : {} < {})", var_name, var_name, rhs_var));
                    let mut after_binds = vec![
                        format!("({} : Nat)", var_name),
                        format!(
                            "(h_{}_val : {} mem {} = {})",
                            var_name, read_fn, addr_expr, var_name
                        ),
                        region_hyp(&var_name, read_fn, &addr_expr),
                    ];
                    after_binds.extend(rhs_bindings);
                    after_binds.push(format!(
                        "(h_{}_ge : \u{00AC}({} < {}))",
                        var_name, var_name, rhs_var
                    ));
                    DerivedHypotheses {
                        bindings,
                        after: Some(after_binds),
                    }
                }
                _ => DerivedHypotheses {
                    bindings: vec![format!("-- TODO: derive hypotheses for checks: {}", checks)],
                    after: None,
                },
            }
        } else {
            // Field not found in layout — generate placeholder
            DerivedHypotheses {
                bindings: vec![format!("-- TODO: derive hypotheses for checks: {}", checks)],
                after: None,
            }
        }
    } else {
        // Complex expression — placeholder
        DerivedHypotheses {
            bindings: vec![format!("-- TODO: derive hypotheses for checks: {}", checks)],
            after: None,
        }
    }
}

/// Prefix hypothesis binder names (starting with `h_`) with `_` to suppress
/// unused-variable warnings in the Spec structure. Value variables like
/// `discriminant`, `nAccounts` etc. must keep their names because hypothesis
/// types reference them (e.g., `readU8 mem addr = discriminant`).
pub(super) fn prefix_unused_binder(binder: &str) -> String {
    if let Some(rest) = binder.strip_prefix("(h_") {
        return format!("(_h_{}", rest);
    }
    binder.to_string()
}

/// Convert error name from qedspec to Lean constant name.
/// E.g., "InvalidDiscriminant" → "E_INVALID_DISCRIMINANT"
pub(super) fn error_to_lean_name(name: &str) -> String {
    let mut result = String::from("E_");
    let mut prev_was_upper = false;
    for (i, c) in name.chars().enumerate() {
        if c.is_uppercase() && i > 0 && !prev_was_upper {
            result.push('_');
        }
        result.push(c.to_ascii_uppercase());
        prev_was_upper = c.is_uppercase();
    }
    result
}

/// Convert layout field name to a Lean variable name.
pub(super) fn field_name_to_var(name: &str) -> String {
    // snake_case → camelCase.
    let parts: Vec<&str> = name.split('_').collect();
    if parts.len() <= 1 {
        return name.to_string();
    }
    let mut result = parts[0].to_string();
    for part in &parts[1..] {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_ascii_uppercase());
            result.extend(chars);
        }
    }
    result
}

/// Convert offset field name to a Lean constant name.
/// Uses naming convention matching qedguards: uppercase with prefix.
pub(super) fn offset_to_lean_name(name: &str) -> String {
    name.to_ascii_uppercase()
}
