// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:c5ccb997d1efeaed
use quasar_lang::prelude::*;

#[error_code]
pub enum MultisigError {
    InvalidThreshold = 0,
    TooManyMembers = 1,
    AlreadyVoted = 2,
    ThresholdNotMet = 3,
    ThresholdUnreachable = 4,
    NotAMember = 5,
    MathOverflow = 6,
    InvalidLifecycle = 7,
    InvalidPda = 8,
}
// ---- END GENERATED ----
