// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:1857eaed3d5aba1b
// Unit tests generated from qedspec.
// These test effects, guards, and properties on a plain state struct.
// No SVM or Quasar runtime required — just `cargo test`.

type Address = [u8; 32];

#[derive(Debug, Clone, PartialEq)]
struct MultisigState {
    creator: [u8; 32],
    threshold: u8,
    member_count: u8,
    members: [[u8; 32]; 32],
    voted: [u8; 32],
    approval_count: u8,
    rejection_count: u8,
}

impl Default for MultisigState {
    fn default() -> Self {
        MultisigState {
            creator: [0u8; 32],
            threshold: 0u8,
            member_count: 0u8,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0u8,
            rejection_count: 0u8,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Status {
    Uninitialized,
    Active,
    HasProposal,
}

/// Apply `create_vault` effects to state.
fn apply_create_vault(state: &mut MultisigState, threshold: u8, member_count: u8) {
    state.threshold = threshold;
    state.member_count = member_count;
    state.approval_count = 0;
    state.rejection_count = 0;
}

/// Apply `propose` effects to state.
fn apply_propose(state: &mut MultisigState) {
    state.approval_count = 0;
    state.rejection_count = 0;
}

/// Apply `approve` effects to state.
fn apply_approve(state: &mut MultisigState, _member_index: u8) {
    state.approval_count += 1;
    state.voted[member_index] = 1;
}

/// Apply `reject` effects to state.
fn apply_reject(state: &mut MultisigState, _member_index: u8) {
    state.rejection_count += 1;
    state.voted[member_index] = 1;
}

/// Apply `execute` effects to state.
fn apply_execute(state: &mut MultisigState, _member_index: u8) {
    state.approval_count = 0;
    state.rejection_count = 0;
}

/// Apply `cancel_proposal` effects to state.
fn apply_cancel_proposal(state: &mut MultisigState) {
    state.approval_count = 0;
    state.rejection_count = 0;
}

/// Apply `add_member` effects to state.
fn apply_add_member(state: &mut MultisigState, _member_index: u8, member_pubkey: [u8; 32]) {
    state.members[member_index] = member_pubkey;
}

/// Apply `remove_member` effects to state.
fn apply_remove_member(state: &mut MultisigState) {
    state.member_count -= 1;
}

/// Guard predicate for `create_vault`.
fn guard_create_vault(_state: &MultisigState, threshold: u8, member_count: u8) -> bool {
    true
}

/// Guard predicate for `approve`.
fn guard_approve(_state: &MultisigState, member_index: u8) -> bool {
    true
}

/// Guard predicate for `reject`.
fn guard_reject(_state: &MultisigState, member_index: u8) -> bool {
    true
}

/// Guard predicate for `execute`.
fn guard_execute(_state: &MultisigState, member_index: u8) -> bool {
    true
}

/// Guard predicate for `cancel_proposal`.
fn guard_cancel_proposal(_state: &MultisigState) -> bool {
    true
}

/// Guard predicate for `add_member`.
fn guard_add_member(_state: &MultisigState, member_index: u8, member_pubkey: [u8; 32]) -> bool {
    true
}

/// Guard predicate for `remove_member`.
fn guard_remove_member(_state: &MultisigState) -> bool {
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    // ====================================================================
    // Effect tests — verify state mutations match spec
    // ====================================================================

    #[test]
    fn test_create_vault_effects() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let threshold: u8 = 3;
        let member_count: u8 = 5;
        apply_create_vault(&mut state, threshold, member_count);
        assert_eq!(state.threshold, threshold);
        assert_eq!(state.member_count, member_count);
        assert_eq!(state.approval_count, 0);
        assert_eq!(state.rejection_count, 0);
    }

    #[test]
    fn test_propose_effects() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        apply_propose(&mut state);
        assert_eq!(state.approval_count, 0);
        assert_eq!(state.rejection_count, 0);
    }

    #[test]
    fn test_approve_effects() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        let pre_approval_count = state.approval_count;
        apply_approve(&mut state, member_index);
        assert_eq!(state.approval_count, pre_approval_count + 1);
        assert_eq!(state.voted[member_index], 1);
    }

    #[test]
    fn test_reject_effects() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        let pre_rejection_count = state.rejection_count;
        apply_reject(&mut state, member_index);
        assert_eq!(state.rejection_count, pre_rejection_count + 1);
        assert_eq!(state.voted[member_index], 1);
    }

    #[test]
    fn test_execute_effects() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        apply_execute(&mut state, member_index);
        assert_eq!(state.approval_count, 0);
        assert_eq!(state.rejection_count, 0);
    }

    #[test]
    fn test_cancel_proposal_effects() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        apply_cancel_proposal(&mut state);
        assert_eq!(state.approval_count, 0);
        assert_eq!(state.rejection_count, 0);
    }

    #[test]
    fn test_add_member_effects() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        let member_pubkey: [u8; 32] = 1;
        apply_add_member(&mut state, member_index, member_pubkey);
        assert_eq!(state.members[member_index], member_pubkey);
    }

    #[test]
    fn test_remove_member_effects() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let pre_member_count = state.member_count;
        apply_remove_member(&mut state);
        assert_eq!(state.member_count, pre_member_count - 1);
    }

    // ====================================================================
    // Guard tests — verify boundary conditions
    // ====================================================================

    #[test]
    fn test_create_vault_guard_accepts_valid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let threshold: u8 = 3;
        let member_count: u8 = 5;
        assert!(guard_create_vault(&state, threshold, member_count));
    }

    #[test]
    fn test_create_vault_guard_rejects_invalid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let threshold: u8 = 0;
        let member_count: u8 = 0;
        assert!(!guard_create_vault(&state, threshold, member_count));
    }

    #[test]
    fn test_approve_guard_accepts_valid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        assert!(guard_approve(&state, member_index));
    }

    #[test]
    fn test_approve_guard_rejects_invalid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        assert!(!guard_approve(&state, member_index));
    }

    #[test]
    fn test_reject_guard_accepts_valid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        assert!(guard_reject(&state, member_index));
    }

    #[test]
    fn test_reject_guard_rejects_invalid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        assert!(!guard_reject(&state, member_index));
    }

    #[test]
    fn test_execute_guard_accepts_valid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        assert!(guard_execute(&state, member_index));
    }

    #[test]
    fn test_execute_guard_rejects_invalid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        assert!(!guard_execute(&state, member_index));
    }

    #[test]
    fn test_cancel_proposal_guard_accepts_valid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        assert!(guard_cancel_proposal(&state));
    }

    #[test]
    fn test_cancel_proposal_guard_rejects_invalid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        assert!(!guard_cancel_proposal(&state));
    }

    #[test]
    fn test_add_member_guard_accepts_valid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        let member_pubkey: [u8; 32] = 1;
        assert!(guard_add_member(&state, member_index, member_pubkey));
    }

    #[test]
    fn test_add_member_guard_rejects_invalid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        let member_pubkey: [u8; 32] = 1;
        assert!(!guard_add_member(&state, member_index, member_pubkey));
    }

    #[test]
    fn test_remove_member_guard_accepts_valid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        assert!(guard_remove_member(&state));
    }

    #[test]
    fn test_remove_member_guard_rejects_invalid() {
        let state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        assert!(!guard_remove_member(&state));
    }

    // ====================================================================
    // Property tests — verify invariants hold after effects
    // ====================================================================

    #[test]
    fn test_create_vault_preserves_threshold_bounded() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let threshold: u8 = 3;
        let member_count: u8 = 5;
        apply_create_vault(&mut state, threshold, member_count);
        // Property: threshold bounded must hold after create_vault
        assert!(state.threshold <= state.member_count && state.threshold > 0, "threshold_bounded must hold after create_vault");
    }

    #[test]
    fn test_propose_preserves_threshold_bounded() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        apply_propose(&mut state);
        // Property: threshold bounded must hold after propose
        assert!(state.threshold <= state.member_count && state.threshold > 0, "threshold_bounded must hold after propose");
    }

    #[test]
    fn test_approve_preserves_threshold_bounded() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        apply_approve(&mut state, member_index);
        // Property: threshold bounded must hold after approve
        assert!(state.threshold <= state.member_count && state.threshold > 0, "threshold_bounded must hold after approve");
    }

    #[test]
    fn test_reject_preserves_threshold_bounded() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        apply_reject(&mut state, member_index);
        // Property: threshold bounded must hold after reject
        assert!(state.threshold <= state.member_count && state.threshold > 0, "threshold_bounded must hold after reject");
    }

    #[test]
    fn test_execute_preserves_threshold_bounded() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        apply_execute(&mut state, member_index);
        // Property: threshold bounded must hold after execute
        assert!(state.threshold <= state.member_count && state.threshold > 0, "threshold_bounded must hold after execute");
    }

    #[test]
    fn test_cancel_proposal_preserves_threshold_bounded() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        apply_cancel_proposal(&mut state);
        // Property: threshold bounded must hold after cancel_proposal
        assert!(state.threshold <= state.member_count && state.threshold > 0, "threshold_bounded must hold after cancel_proposal");
    }

    #[test]
    fn test_add_member_preserves_threshold_bounded() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        let member_pubkey: [u8; 32] = 1;
        apply_add_member(&mut state, member_index, member_pubkey);
        // Property: threshold bounded must hold after add_member
        assert!(state.threshold <= state.member_count && state.threshold > 0, "threshold_bounded must hold after add_member");
    }

    #[test]
    fn test_remove_member_preserves_threshold_bounded() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        apply_remove_member(&mut state);
        // Property: threshold bounded must hold after remove_member
        assert!(state.threshold <= state.member_count && state.threshold > 0, "threshold_bounded must hold after remove_member");
    }

    #[test]
    fn test_create_vault_preserves_votes_bounded() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let threshold: u8 = 3;
        let member_count: u8 = 5;
        apply_create_vault(&mut state, threshold, member_count);
        // Property: votes bounded must hold after create_vault
        assert!(state.approval_count + state.rejection_count <= state.member_count, "votes_bounded must hold after create_vault");
    }

    #[test]
    fn test_propose_preserves_votes_bounded() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        apply_propose(&mut state);
        // Property: votes bounded must hold after propose
        assert!(state.approval_count + state.rejection_count <= state.member_count, "votes_bounded must hold after propose");
    }

    #[test]
    fn test_execute_preserves_votes_bounded() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        apply_execute(&mut state, member_index);
        // Property: votes bounded must hold after execute
        assert!(state.approval_count + state.rejection_count <= state.member_count, "votes_bounded must hold after execute");
    }

    #[test]
    fn test_cancel_proposal_preserves_votes_bounded() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        apply_cancel_proposal(&mut state);
        // Property: votes bounded must hold after cancel_proposal
        assert!(state.approval_count + state.rejection_count <= state.member_count, "votes_bounded must hold after cancel_proposal");
    }

    #[test]
    fn test_remove_member_preserves_votes_bounded() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        apply_remove_member(&mut state);
        // Property: votes bounded must hold after remove_member
        assert!(state.approval_count + state.rejection_count <= state.member_count, "votes_bounded must hold after remove_member");
    }

    // ====================================================================
    // Unchanged field tests — fields not in effects must not change
    // ====================================================================

    #[test]
    fn test_create_vault_unchanged_fields() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let threshold: u8 = 3;
        let member_count: u8 = 5;
        let pre_members = state.members.clone();
        let pre_voted = state.voted.clone();
        apply_create_vault(&mut state, threshold, member_count);
        assert_eq!(state.members, pre_members, "members must not change after create_vault");
        assert_eq!(state.voted, pre_voted, "voted must not change after create_vault");
    }

    #[test]
    fn test_propose_unchanged_fields() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let pre_threshold = state.threshold.clone();
        let pre_member_count = state.member_count.clone();
        let pre_members = state.members.clone();
        let pre_voted = state.voted.clone();
        apply_propose(&mut state);
        assert_eq!(state.threshold, pre_threshold, "threshold must not change after propose");
        assert_eq!(state.member_count, pre_member_count, "member_count must not change after propose");
        assert_eq!(state.members, pre_members, "members must not change after propose");
        assert_eq!(state.voted, pre_voted, "voted must not change after propose");
    }

    #[test]
    fn test_approve_unchanged_fields() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        let pre_threshold = state.threshold.clone();
        let pre_member_count = state.member_count.clone();
        let pre_members = state.members.clone();
        let pre_voted = state.voted.clone();
        let pre_rejection_count = state.rejection_count.clone();
        apply_approve(&mut state, member_index);
        assert_eq!(state.threshold, pre_threshold, "threshold must not change after approve");
        assert_eq!(state.member_count, pre_member_count, "member_count must not change after approve");
        assert_eq!(state.members, pre_members, "members must not change after approve");
        assert_eq!(state.voted, pre_voted, "voted must not change after approve");
        assert_eq!(state.rejection_count, pre_rejection_count, "rejection_count must not change after approve");
    }

    #[test]
    fn test_reject_unchanged_fields() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        let pre_threshold = state.threshold.clone();
        let pre_member_count = state.member_count.clone();
        let pre_members = state.members.clone();
        let pre_voted = state.voted.clone();
        let pre_approval_count = state.approval_count.clone();
        apply_reject(&mut state, member_index);
        assert_eq!(state.threshold, pre_threshold, "threshold must not change after reject");
        assert_eq!(state.member_count, pre_member_count, "member_count must not change after reject");
        assert_eq!(state.members, pre_members, "members must not change after reject");
        assert_eq!(state.voted, pre_voted, "voted must not change after reject");
        assert_eq!(state.approval_count, pre_approval_count, "approval_count must not change after reject");
    }

    #[test]
    fn test_execute_unchanged_fields() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        let pre_threshold = state.threshold.clone();
        let pre_member_count = state.member_count.clone();
        let pre_members = state.members.clone();
        let pre_voted = state.voted.clone();
        apply_execute(&mut state, member_index);
        assert_eq!(state.threshold, pre_threshold, "threshold must not change after execute");
        assert_eq!(state.member_count, pre_member_count, "member_count must not change after execute");
        assert_eq!(state.members, pre_members, "members must not change after execute");
        assert_eq!(state.voted, pre_voted, "voted must not change after execute");
    }

    #[test]
    fn test_cancel_proposal_unchanged_fields() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let pre_threshold = state.threshold.clone();
        let pre_member_count = state.member_count.clone();
        let pre_members = state.members.clone();
        let pre_voted = state.voted.clone();
        apply_cancel_proposal(&mut state);
        assert_eq!(state.threshold, pre_threshold, "threshold must not change after cancel_proposal");
        assert_eq!(state.member_count, pre_member_count, "member_count must not change after cancel_proposal");
        assert_eq!(state.members, pre_members, "members must not change after cancel_proposal");
        assert_eq!(state.voted, pre_voted, "voted must not change after cancel_proposal");
    }

    #[test]
    fn test_add_member_unchanged_fields() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let member_index: u8 = 0;
        let member_pubkey: [u8; 32] = 1;
        let pre_threshold = state.threshold.clone();
        let pre_member_count = state.member_count.clone();
        let pre_members = state.members.clone();
        let pre_voted = state.voted.clone();
        let pre_approval_count = state.approval_count.clone();
        let pre_rejection_count = state.rejection_count.clone();
        apply_add_member(&mut state, member_index, member_pubkey);
        assert_eq!(state.threshold, pre_threshold, "threshold must not change after add_member");
        assert_eq!(state.member_count, pre_member_count, "member_count must not change after add_member");
        assert_eq!(state.members, pre_members, "members must not change after add_member");
        assert_eq!(state.voted, pre_voted, "voted must not change after add_member");
        assert_eq!(state.approval_count, pre_approval_count, "approval_count must not change after add_member");
        assert_eq!(state.rejection_count, pre_rejection_count, "rejection_count must not change after add_member");
    }

    #[test]
    fn test_remove_member_unchanged_fields() {
        let mut state = MultisigState {
            creator: [1u8; 32],
            threshold: 3,
            member_count: 5,
            members: Default::default(),
            voted: Default::default(),
            approval_count: 0,
            rejection_count: 0,
        };
        let pre_threshold = state.threshold.clone();
        let pre_members = state.members.clone();
        let pre_voted = state.voted.clone();
        let pre_approval_count = state.approval_count.clone();
        let pre_rejection_count = state.rejection_count.clone();
        apply_remove_member(&mut state);
        assert_eq!(state.threshold, pre_threshold, "threshold must not change after remove_member");
        assert_eq!(state.members, pre_members, "members must not change after remove_member");
        assert_eq!(state.voted, pre_voted, "voted must not change after remove_member");
        assert_eq!(state.approval_count, pre_approval_count, "approval_count must not change after remove_member");
        assert_eq!(state.rejection_count, pre_rejection_count, "rejection_count must not change after remove_member");
    }

    // ====================================================================
    // State machine tests — verify lifecycle transitions
    // ====================================================================

    #[test]
    fn test_create_vault_transition_uninitialized_to_active() {
        // create_vault requires status == Uninitialized and moves to Active
        assert_ne!(Status::Uninitialized, Status::Active, "create_vault changes status");
        let _pre = Status::Uninitialized;
        let _post = Status::Active;
        // AGENT: verify handler transitions status from _pre to _post
    }

    #[test]
    fn test_propose_transition_active_to_hasproposal() {
        // propose requires status == Active and moves to HasProposal
        assert_ne!(Status::Active, Status::HasProposal, "propose changes status");
        let _pre = Status::Active;
        let _post = Status::HasProposal;
        // AGENT: verify handler transitions status from _pre to _post
    }

    #[test]
    fn test_approve_transition_hasproposal_to_hasproposal() {
        // approve requires status == HasProposal and moves to HasProposal
        assert_eq!(Status::HasProposal, Status::HasProposal, "approve is a self-transition");
        let _pre = Status::HasProposal;
        let _post = Status::HasProposal;
        // AGENT: verify handler transitions status from _pre to _post
    }

    #[test]
    fn test_reject_transition_hasproposal_to_hasproposal() {
        // reject requires status == HasProposal and moves to HasProposal
        assert_eq!(Status::HasProposal, Status::HasProposal, "reject is a self-transition");
        let _pre = Status::HasProposal;
        let _post = Status::HasProposal;
        // AGENT: verify handler transitions status from _pre to _post
    }

    #[test]
    fn test_execute_transition_hasproposal_to_active() {
        // execute requires status == HasProposal and moves to Active
        assert_ne!(Status::HasProposal, Status::Active, "execute changes status");
        let _pre = Status::HasProposal;
        let _post = Status::Active;
        // AGENT: verify handler transitions status from _pre to _post
    }

    #[test]
    fn test_cancel_proposal_transition_hasproposal_to_active() {
        // cancel_proposal requires status == HasProposal and moves to Active
        assert_ne!(Status::HasProposal, Status::Active, "cancel_proposal changes status");
        let _pre = Status::HasProposal;
        let _post = Status::Active;
        // AGENT: verify handler transitions status from _pre to _post
    }

    #[test]
    fn test_add_member_transition_active_to_active() {
        // add_member requires status == Active and moves to Active
        assert_eq!(Status::Active, Status::Active, "add_member is a self-transition");
        let _pre = Status::Active;
        let _post = Status::Active;
        // AGENT: verify handler transitions status from _pre to _post
    }

    #[test]
    fn test_remove_member_transition_active_to_active() {
        // remove_member requires status == Active and moves to Active
        assert_eq!(Status::Active, Status::Active, "remove_member is a self-transition");
        let _pre = Status::Active;
        let _post = Status::Active;
        // AGENT: verify handler transitions status from _pre to _post
    }

}
