// ---- GENERATED BY QEDGEN — DO NOT EDIT — regenerated from .qedspec ----
//! Per-handler guard checks derived from the `.qedspec`.
//! Called from user-owned `instructions/<name>::handler` before
//! business logic; keep guard logic here, policy-free logic there.

#![allow(unused_variables, unused_imports, dead_code, clippy::too_many_arguments)]

use quasar_lang::prelude::*;
use crate::errors::*;
use crate::state::*;
use crate::math::*;
use crate::instructions::*;

/// Guards for `add_user`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn add_user<'info>(ctx: &mut AddUser<'info>, i: usize) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.accounts[i].active = 0
    if !(ctx.vault.accounts[(i) as usize].active == 0) { return Err(ProgramError::from(PercolatorError::SlotAlreadyActive)); }
    // requires: (((s.accounts[i].capital) : Int)) + s.accounts[i].pnl ≥ (((0) : Int))
    if !(((((ctx.vault.accounts[(i) as usize].capital.get()) as i128) + ((ctx.vault.accounts[(i) as usize].pnl.get()) as i128)) as i128) >= ((0) as i128)) { return Err(ProgramError::from(PercolatorError::AccountUnderwater)); }
    Ok(())
}

/// Guards for `add_lp`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn add_lp<'info>(ctx: &mut AddLp<'info>, i: usize) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.accounts[i].active = 0
    if !(ctx.vault.accounts[(i) as usize].active == 0) { return Err(ProgramError::from(PercolatorError::SlotAlreadyActive)); }
    // requires: (((s.accounts[i].capital) : Int)) + s.accounts[i].pnl ≥ (((0) : Int))
    if !(((((ctx.vault.accounts[(i) as usize].capital.get()) as i128) + ((ctx.vault.accounts[(i) as usize].pnl.get()) as i128)) as i128) >= ((0) as i128)) { return Err(ProgramError::from(PercolatorError::AccountUnderwater)); }
    Ok(())
}

/// Guards for `reclaim_empty_account`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn reclaim_empty_account<'info>(ctx: &mut ReclaimEmptyAccount<'info>, i: usize) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[(i) as usize].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.accounts[i].capital = 0
    if !(ctx.vault.accounts[(i) as usize].capital.get() == 0) { return Err(ProgramError::Custom(0xFF)); }
    // requires: s.accounts[i].reserved_pnl = 0
    if !(ctx.vault.accounts[(i) as usize].reserved_pnl.get() == 0) { return Err(ProgramError::Custom(0xFF)); }
    // requires: s.accounts[i].fee_credits = 0
    if !(ctx.vault.accounts[(i) as usize].fee_credits.get() == 0) { return Err(ProgramError::Custom(0xFF)); }
    Ok(())
}

/// Guards for `close_account`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn close_account<'info>(ctx: &mut CloseAccount<'info>, i: usize) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[(i) as usize].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.V ≥ s.accounts[i].capital
    if !(ctx.vault.V.get() >= ctx.vault.accounts[(i) as usize].capital.get()) { return Err(ProgramError::from(PercolatorError::InsufficientFunds)); }
    Ok(())
}

/// Guards for `deposit`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn deposit<'info>(ctx: &mut Deposit<'info>, i: usize, amount: u128) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[(i) as usize].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.V + amount ≤ 10000000000000000
    if !(ctx.vault.V.get() + amount <= 10000000000000000) { return Err(ProgramError::from(PercolatorError::VaultOverflow)); }
    Ok(())
}

/// Guards for `withdraw`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn withdraw<'info>(ctx: &mut Withdraw<'info>, i: usize, amount: u128) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[(i) as usize].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.accounts[i].capital ≥ amount
    if !(ctx.vault.accounts[(i) as usize].capital.get() >= amount) { return Err(ProgramError::from(PercolatorError::InsufficientFunds)); }
    // requires: (((s.accounts[i].capital) : Int)) + s.accounts[i].pnl ≥ (((amount) : Int))
    if !(((((ctx.vault.accounts[(i) as usize].capital.get()) as i128) + ((ctx.vault.accounts[(i) as usize].pnl.get()) as i128)) as i128) >= ((amount) as i128)) { return Err(ProgramError::from(PercolatorError::InsufficientFunds)); }
    Ok(())
}

/// Guards for `top_up_insurance`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn top_up_insurance<'info>(ctx: &mut TopUpInsurance<'info>, amount: u128) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.V + amount ≤ 10000000000000000
    if !(ctx.vault.V.get() + amount <= 10000000000000000) { return Err(ProgramError::from(PercolatorError::VaultOverflow)); }
    Ok(())
}

/// Guards for `deposit_fee_credits`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn deposit_fee_credits<'info>(ctx: &mut DepositFeeCredits<'info>, i: usize, amount: u128) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[(i) as usize].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.V + amount ≤ 10000000000000000
    if !(ctx.vault.V.get() + amount <= 10000000000000000) { return Err(ProgramError::from(PercolatorError::VaultOverflow)); }
    Ok(())
}

/// Guards for `convert_released_pnl`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn convert_released_pnl<'info>(ctx: &mut ConvertReleasedPnl<'info>, i: usize, x: u128) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[(i) as usize].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.accounts[i].reserved_pnl ≥ x
    if !(ctx.vault.accounts[(i) as usize].reserved_pnl.get() >= x) { return Err(ProgramError::from(PercolatorError::InsufficientFunds)); }
    // requires: s.V ≥ x
    if !(ctx.vault.V.get() >= x) { return Err(ProgramError::from(PercolatorError::InsufficientFunds)); }
    Ok(())
}

/// Guards for `execute_trade`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn execute_trade<'info>(ctx: &mut ExecuteTrade<'info>, a: usize, b: usize, size_q: i128, exec_price: u64) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.accounts[a].active = 1
    if !(ctx.vault.accounts[(a) as usize].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.accounts[b].active = 1
    if !(ctx.vault.accounts[(b) as usize].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: a ≠ b
    if !(a != b) { return Err(ProgramError::Custom(0xFF)); }
    // requires: (((size_q) * ((((exec_price) : Int)))) / (1000000)) ≤ (((100000000000000000000) : Int))
    if !(mul_div_floor_u128(((size_q) as u128), ((exec_price) as u128), ((1000000) as u128)) <= 100000000000000000000) { return Err(ProgramError::Custom(0xFF)); }
    Ok(())
}

/// Guards for `liquidate_case_0`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn liquidate_case_0<'info>(ctx: &mut LiquidateCase0<'info>, i: usize) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[(i) as usize].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: (((s.accounts[i].capital) : Int)) + s.accounts[i].pnl ≥ (((0) : Int))
    if !(((((ctx.vault.accounts[(i) as usize].capital.get()) as i128) + ((ctx.vault.accounts[(i) as usize].pnl.get()) as i128)) as i128) >= ((0) as i128)) { return Err(ProgramError::Custom(0xFF)); }
    // requires: 0 = 1
    if !(false) { return Err(ProgramError::from(PercolatorError::AccountHealthy)); }
    Ok(())
}

/// Guards for `liquidate_case_1`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn liquidate_case_1<'info>(ctx: &mut LiquidateCase1<'info>, i: usize) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[(i) as usize].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: ¬((((s.accounts[i].capital) : Int)) + s.accounts[i].pnl ≥ (((0) : Int)))
    if !(!(((((ctx.vault.accounts[(i) as usize].capital.get()) as i128) + ((ctx.vault.accounts[(i) as usize].pnl.get()) as i128)) as i128) >= ((0) as i128))) { return Err(ProgramError::Custom(0xFF)); }
    // requires: (((s.accounts[i].capital) : Int)) + s.accounts[i].pnl + (((s.I) : Int)) ≥ (((0) : Int))
    if !(((((((ctx.vault.accounts[(i) as usize].capital.get()) as i128) + ((ctx.vault.accounts[(i) as usize].pnl.get()) as i128)) as i128) + ((ctx.vault.I.get()) as i128)) as i128) >= ((0) as i128)) { return Err(ProgramError::Custom(0xFF)); }
    Ok(())
}

/// Guards for `liquidate_otherwise`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn liquidate_otherwise<'info>(ctx: &mut LiquidateOtherwise<'info>, i: usize) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[(i) as usize].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: ¬((((s.accounts[i].capital) : Int)) + s.accounts[i].pnl ≥ (((0) : Int)))
    if !(!(((((ctx.vault.accounts[(i) as usize].capital.get()) as i128) + ((ctx.vault.accounts[(i) as usize].pnl.get()) as i128)) as i128) >= ((0) as i128))) { return Err(ProgramError::Custom(0xFF)); }
    // requires: ¬((((s.accounts[i].capital) : Int)) + s.accounts[i].pnl + (((s.I) : Int)) ≥ (((0) : Int)))
    if !(!(((((((ctx.vault.accounts[(i) as usize].capital.get()) as i128) + ((ctx.vault.accounts[(i) as usize].pnl.get()) as i128)) as i128) + ((ctx.vault.I.get()) as i128)) as i128) >= ((0) as i128))) { return Err(ProgramError::Custom(0xFF)); }
    // requires: 0 = 1
    if !(false) { return Err(ProgramError::from(PercolatorError::BankruptPosition)); }
    Ok(())
}

/// Guards for `settle_account`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn settle_account<'info>(ctx: &mut SettleAccount<'info>, i: usize) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[(i) as usize].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    Ok(())
}

/// Guards for `trigger_adl`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn trigger_adl<'info>(ctx: &mut TriggerAdl<'info>) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.vault.status != Status::Active as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // lifecycle: status := Draining
    ctx.vault.status = Status::Draining as u8;
    Ok(())
}

/// Guards for `complete_drain`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn complete_drain<'info>(ctx: &mut CompleteDrain<'info>) -> Result<(), ProgramError> {
    // lifecycle: require status == Draining
    if ctx.vault.status != Status::Draining as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // lifecycle: status := Resetting
    ctx.vault.status = Status::Resetting as u8;
    Ok(())
}

/// Guards for `reset`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn reset<'info>(ctx: &mut Reset<'info>) -> Result<(), ProgramError> {
    // lifecycle: require status == Resetting
    if ctx.vault.status != Status::Resetting as u8 { return Err(ProgramError::from(crate::errors::PercolatorError::InvalidLifecycle)); }
    // lifecycle: status := Active
    ctx.vault.status = Status::Active as u8;
    Ok(())
}

// ---- END GENERATED ----
