// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:f1285c28093087c9
#![cfg_attr(any(target_os = "solana", target_arch = "bpf"), no_std)]

use quasar_lang::prelude::*;

mod instructions;
use instructions::*;
pub mod errors;
pub mod state;
pub mod guards;
pub mod math;

declare_id!("11111111111111111111111111111111");

#[program]
mod percolator {
    use super::*;

    #[instruction(discriminator = 0)]
    pub fn add_user(ctx: Ctx<AddUser>, i: u32) -> Result<(), ProgramError> {
        ctx.accounts.handler(i as usize)
    }

    #[instruction(discriminator = 1)]
    pub fn add_lp(ctx: Ctx<AddLp>, i: u32) -> Result<(), ProgramError> {
        ctx.accounts.handler(i as usize)
    }

    #[instruction(discriminator = 2)]
    pub fn reclaim_empty_account(ctx: Ctx<ReclaimEmptyAccount>, i: u32) -> Result<(), ProgramError> {
        ctx.accounts.handler(i as usize)
    }

    #[instruction(discriminator = 3)]
    pub fn close_account(ctx: Ctx<CloseAccount>, i: u32) -> Result<(), ProgramError> {
        ctx.accounts.handler(i as usize)
    }

    #[instruction(discriminator = 4)]
    pub fn deposit(ctx: Ctx<Deposit>, i: u32, amount: u128) -> Result<(), ProgramError> {
        ctx.accounts.handler(i as usize, amount)
    }

    #[instruction(discriminator = 5)]
    pub fn withdraw(ctx: Ctx<Withdraw>, i: u32, amount: u128) -> Result<(), ProgramError> {
        ctx.accounts.handler(i as usize, amount)
    }

    #[instruction(discriminator = 6)]
    pub fn top_up_insurance(ctx: Ctx<TopUpInsurance>, amount: u128) -> Result<(), ProgramError> {
        ctx.accounts.handler(amount)
    }

    #[instruction(discriminator = 7)]
    pub fn deposit_fee_credits(ctx: Ctx<DepositFeeCredits>, i: u32, amount: u128) -> Result<(), ProgramError> {
        ctx.accounts.handler(i as usize, amount)
    }

    #[instruction(discriminator = 8)]
    pub fn convert_released_pnl(ctx: Ctx<ConvertReleasedPnl>, i: u32, x: u128) -> Result<(), ProgramError> {
        ctx.accounts.handler(i as usize, x)
    }

    #[instruction(discriminator = 9)]
    pub fn execute_trade(ctx: Ctx<ExecuteTrade>, a: u32, b: u32, size_q: i128, exec_price: u64) -> Result<(), ProgramError> {
        ctx.accounts.handler(a as usize, b as usize, size_q, exec_price)
    }

    #[instruction(discriminator = 10)]
    pub fn liquidate_case_0(ctx: Ctx<LiquidateCase0>, i: u32) -> Result<(), ProgramError> {
        ctx.accounts.handler(i as usize)
    }

    #[instruction(discriminator = 11)]
    pub fn liquidate_case_1(ctx: Ctx<LiquidateCase1>, i: u32) -> Result<(), ProgramError> {
        ctx.accounts.handler(i as usize)
    }

    #[instruction(discriminator = 12)]
    pub fn liquidate_otherwise(ctx: Ctx<LiquidateOtherwise>, i: u32) -> Result<(), ProgramError> {
        ctx.accounts.handler(i as usize)
    }

    #[instruction(discriminator = 13)]
    pub fn settle_account(ctx: Ctx<SettleAccount>, i: u32) -> Result<(), ProgramError> {
        ctx.accounts.handler(i as usize)
    }

    #[instruction(discriminator = 14)]
    pub fn trigger_adl(ctx: Ctx<TriggerAdl>) -> Result<(), ProgramError> {
        ctx.accounts.handler()
    }

    #[instruction(discriminator = 15)]
    pub fn complete_drain(ctx: Ctx<CompleteDrain>) -> Result<(), ProgramError> {
        ctx.accounts.handler()
    }

    #[instruction(discriminator = 16)]
    pub fn reset(ctx: Ctx<Reset>) -> Result<(), ProgramError> {
        ctx.accounts.handler()
    }

}
// ---- END GENERATED ----
