// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:05ab8da85801148c
use quasar_lang::prelude::*;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct Account {
    pub active: u8,
    pub capital: PodU128,
    pub reserved_pnl: PodU128,
    pub pnl: PodI128,
    pub fee_credits: PodU128,
}

#[account(discriminator = 1)]
pub struct PercolatorAccount {
    pub authority: Pubkey,
    pub V: u128,
    pub I: u128,
    pub F: u128,
    pub accounts: [Account; 1024],
    pub status: u8,
}

/// Program lifecycle states.
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Status {
    Active = 0,
    Draining = 1,
    Resetting = 2,
}
// ---- END GENERATED ----
