-- Auto-generated by qedgen asm2lean from asm-slippage.s
-- DO NOT EDIT — regenerate with: qedgen asm2lean --input asm-slippage.s
-- source-hash: sha256:d10a405b4edfe2327aa6c6c584e285dcb40040e66cd039f0ba40fda3e1e1039f

import SVM.SBPF

namespace SlippageProg

open SVM.SBPF

/-! ## .equ constants -/

abbrev TOKEN_ACCOUNT_BALANCE : Int := 0xa0
abbrev MINIMUM_BALANCE : Int := 0x2918

/-! ## .rodata symbols

Laid out in the program region: `BYTECODE_START` (0x100000000) + .text size
(12 binary slots × 8 bytes; `lddw` occupies 2 slots). Deployed VAs additionally
include ELF header/section offsets a source-level lift cannot see, so proofs
MUST reference these symbols by name — a corrected base only shifts the
numerals. Fidelity to the deployed binary is the binary lane's job (qedlift). -/

/-- `e` at rodata offset 0x0: "Slippage exceeded" -/
abbrev RODATA_e : Nat := 0x100000060
abbrev RODATA_e_LEN : Nat := 17
def RODATA_e_BYTES : ByteArray := ⟨#[0x53, 0x6c, 0x69, 0x70, 0x70, 0x61, 0x67, 0x65, 0x20, 0x65, 0x78, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64]⟩

/-! ## effectiveAddr lemmas -/

section EffectiveAddr

open SVM.SBPF.Memory

@[simp] theorem ea_MINIMUM_BALANCE (b : Nat) : effectiveAddr b MINIMUM_BALANCE = b + 10520 := by
  unfold effectiveAddr MINIMUM_BALANCE; omega

@[simp] theorem ea_TOKEN_ACCOUNT_BALANCE (b : Nat) : effectiveAddr b TOKEN_ACCOUNT_BALANCE = b + 160 := by
  unfold effectiveAddr TOKEN_ACCOUNT_BALANCE; omega

end EffectiveAddr

/-! ## toU64 bridge lemmas (lddw constants) -/

@[simp] theorem bridge_RODATA_e : toU64 (↑RODATA_e : Int) = RODATA_e := by native_decide

/-! ## Program -/

@[simp] def prog : Program := #[
  .ldx .dword .r3 .r1 MINIMUM_BALANCE,             -- 0: entrypoint
  .ldx .dword .r4 .r1 TOKEN_ACCOUNT_BALANCE,       -- 1
  .jge .r3 (.reg .r4) 4,                           -- 2
  .exit,                                           -- 3
  .lddw .r1 RODATA_e,                              -- 4: end
  .lddw .r2 17,                                    -- 5
  .call .sol_log_,                                 -- 6
  .lddw .r0 1,                                     -- 7
  .exit                                             -- 8
]

@[simp] def progAt : Nat → Option SVM.SBPF.Insn
  | 0 => some (.ldx .dword .r3 .r1 MINIMUM_BALANCE)
  | 1 => some (.ldx .dword .r4 .r1 TOKEN_ACCOUNT_BALANCE)
  | 2 => some (.jge .r3 (.reg .r4) 4)
  | 3 => some (.exit)
  | 4 => some (.lddw .r1 RODATA_e)
  | 5 => some (.lddw .r2 17)
  | 6 => some (.call .sol_log_)
  | 7 => some (.lddw .r0 1)
  | 8 => some (.exit)
  | _ => none

/-! ## Instruction fetch cache -/

@[simp] theorem insn_0 : progAt 0 = some (.ldx .dword .r3 .r1 MINIMUM_BALANCE) := by native_decide
@[simp] theorem insn_1 : progAt 1 = some (.ldx .dword .r4 .r1 TOKEN_ACCOUNT_BALANCE) := by native_decide
@[simp] theorem insn_2 : progAt 2 = some (.jge .r3 (.reg .r4) 4) := by native_decide
@[simp] theorem insn_3 : progAt 3 = some (.exit) := by native_decide
@[simp] theorem insn_4 : progAt 4 = some (.lddw .r1 RODATA_e) := by native_decide
@[simp] theorem insn_5 : progAt 5 = some (.lddw .r2 17) := by native_decide
@[simp] theorem insn_6 : progAt 6 = some (.call .sol_log_) := by native_decide
@[simp] theorem insn_7 : progAt 7 = some (.lddw .r0 1) := by native_decide
@[simp] theorem insn_8 : progAt 8 = some (.exit) := by native_decide

end SlippageProg
