// ---- GENERATED BY QEDGEN ---- spec-hash:9a2e9ca10ae52fa8
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

#[derive(Clone, Copy, PartialEq, Eq, kani::Arbitrary)]
enum Status {
    Uninitialized,
    Open,
}

#[derive(Clone, Copy)]
struct State {
    pool_balance: u64,
    status: Status,
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn initialize(s: &mut State, initial: u64) -> bool {
    if !(initial > 0) {
        return false;
    }
    if s.status != Status::Uninitialized {
        return false;
    }
    s.pool_balance = initial;
    s.status = Status::Open;
    true
}

fn deposit(s: &mut State, amount: u64) -> bool {
    if !(amount > 0) {
        return false;
    }
    if s.status != Status::Open {
        return false;
    }
    match s.pool_balance.checked_add(amount) {
        Some(__v) => s.pool_balance = __v,
        None => return false,
    }
    s.status = Status::Open;
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_rejects_invalid() {
    let mut s = State {
        pool_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Uninitialized);
    let initial: u64 = kani::any();
    kani::assume(!(initial > 0));
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !initialize(&mut s, initial),
        "initialize must reject when guard is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_rejects_invalid() {
    let mut s = State {
        pool_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Open);
    let amount: u64 = kani::any();
    kani::assume(!(amount > 0));
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !deposit(&mut s, amount),
        "deposit must reject when guard is violated"
    );
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_effect_pool_balance() {
    let mut s = State {
        pool_balance: 0,
        status: Status::Uninitialized,
    };
    let initial: u64 = kani::any();
    if initialize(&mut s, initial) {
        assert!(s.pool_balance == initial, "pool_balance must equal initial");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_effect_pool_balance() {
    let mut s = State {
        pool_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Open);
    let amount: u64 = kani::any();
    let pre_pool_balance = s.pool_balance;
    if deposit(&mut s, amount) {
        assert!(
            s.pool_balance == pre_pool_balance.wrapping_add(amount),
            "pool_balance must increment by amount"
        );
    }
}

// ============================================================================
// Overflow detection — Kani catches arithmetic overflow on add effects
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_no_overflow() {
    let mut s = State {
        pool_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Open);
    let amount: u64 = kani::any();
    deposit(&mut s, amount); // Kani detects overflow on += internally
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
