// ---- GENERATED BY QEDGEN ---- spec-hash:6bf5a04faca9f21d
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

use qedgen_kani_prelude::mul_bps_floor_u128;

#[allow(dead_code)]
fn pubkey_eq(a: &[u8; 32], b: &[u8; 32]) -> bool {
    a[0] == b[0]
        && a[1] == b[1]
        && a[2] == b[2]
        && a[3] == b[3]
        && a[4] == b[4]
        && a[5] == b[5]
        && a[6] == b[6]
        && a[7] == b[7]
        && a[8] == b[8]
        && a[9] == b[9]
        && a[10] == b[10]
        && a[11] == b[11]
        && a[12] == b[12]
        && a[13] == b[13]
        && a[14] == b[14]
        && a[15] == b[15]
        && a[16] == b[16]
        && a[17] == b[17]
        && a[18] == b[18]
        && a[19] == b[19]
        && a[20] == b[20]
        && a[21] == b[21]
        && a[22] == b[22]
        && a[23] == b[23]
        && a[24] == b[24]
        && a[25] == b[25]
        && a[26] == b[26]
        && a[27] == b[27]
        && a[28] == b[28]
        && a[29] == b[29]
        && a[30] == b[30]
        && a[31] == b[31]
}

#[allow(dead_code)]
fn pubkey_ne(a: &[u8; 32], b: &[u8; 32]) -> bool {
    !pubkey_eq(a, b)
}

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

#[derive(Clone, Copy, PartialEq, Eq, kani::Arbitrary)]
enum Status {
    Uninitialized,
    Active,
}

#[derive(Clone, Copy)]
struct State {
    admin_key: [u8; 32],
    pool_balance: u64,
    user_balance: u64,
    status: Status,
}

#[derive(Clone, Copy)]
struct KaniAccount {
    pubkey: [u8; 32],
}

#[derive(Clone, Copy)]
struct InitializeAccounts {
    admin: KaniAccount,
}

#[derive(Clone, Copy)]
struct UnboundTransferAccounts {
    admin: KaniAccount,
    pool_ta: KaniAccount,
    user_ta: KaniAccount,
    token_program: KaniAccount,
}

#[derive(Clone, Copy)]
struct BoundTransferAccounts {
    admin: KaniAccount,
    pool_ta: KaniAccount,
    user_ta: KaniAccount,
    token_program: KaniAccount,
}

#[derive(Clone, Copy)]
struct StableSwapLargeGuardAccounts {
    admin: KaniAccount,
    pool_ta: KaniAccount,
    user_ta: KaniAccount,
    token_program: KaniAccount,
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn initialize(s: &mut State, accounts: &InitializeAccounts) -> bool {
    if s.status != Status::Uninitialized {
        return false;
    }
    s.admin_key = accounts.admin.pubkey;
    s.pool_balance = 0;
    s.user_balance = 0;
    s.status = Status::Active;
    true
}

fn unbound_transfer(s: &mut State, accounts: &UnboundTransferAccounts, amount: u64) -> bool {
    if !(pubkey_eq(&accounts.admin.pubkey, &s.admin_key) && amount > 0) {
        return false;
    }
    if s.status != Status::Active {
        return false;
    }
    s.status = Status::Active;
    true
}

fn bound_transfer(s: &mut State, accounts: &BoundTransferAccounts, amount: u64) -> bool {
    if !(pubkey_eq(&accounts.admin.pubkey, &s.admin_key) && amount > 0) {
        return false;
    }
    if s.status != Status::Active {
        return false;
    }
    match s.pool_balance.checked_sub(amount) {
        Some(__v) => s.pool_balance = __v,
        None => return false,
    }
    match s.user_balance.checked_add(amount) {
        Some(__v) => s.user_balance = __v,
        None => return false,
    }
    s.status = Status::Active;
    true
}

fn stable_swap_large_guard(
    s: &mut State,
    accounts: &StableSwapLargeGuardAccounts,
    amount_in: u128,
    min_out: u128,
    fee_bps: u128,
    lane: u8,
    input_mint: [u8; 32],
    output_mint: [u8; 32],
) -> bool {
    if !(pubkey_eq(&accounts.admin.pubkey, &s.admin_key)) {
        return false;
    }
    if amount_in <= 0 {
        return false;
    }
    if min_out <= 0 {
        return false;
    }
    if fee_bps > 10000 {
        return false;
    }
    if lane >= 32 {
        return false;
    }
    if !(pubkey_ne(&input_mint, &output_mint)) {
        return false;
    }
    if !(pubkey_eq(&input_mint, &output_mint) || amount_in >= min_out) {
        return false;
    }
    if mul_bps_floor_u128(amount_in, fee_bps) > amount_in {
        return false;
    }
    if amount_in < min_out {
        return false;
    }
    if amount_in > 1000000000000000 {
        return false;
    }
    if s.status != Status::Active {
        return false;
    }
    s.status = Status::Active;
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_unbound_transfer_rejects_invalid() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    let accounts = UnboundTransferAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(!(pubkey_eq(&accounts.admin.pubkey, &s.admin_key) && amount > 0));
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !unbound_transfer(&mut s, &accounts, amount),
        "unbound_transfer must reject when guard is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_bound_transfer_rejects_invalid() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    let accounts = BoundTransferAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(!(pubkey_eq(&accounts.admin.pubkey, &s.admin_key) && amount > 0));
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !bound_transfer(&mut s, &accounts, amount),
        "bound_transfer must reject when guard is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_stable_swap_large_guard_rejects_invalid_1_pubkey_eq_accounts_admin_pubkey_s_admin_key() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount_in: u128 = kani::any();
    let min_out: u128 = kani::any();
    let fee_bps: u128 = kani::any();
    let lane: u8 = kani::any();
    let input_mint: [u8; 32] = kani::any();
    let output_mint: [u8; 32] = kani::any();
    let accounts = StableSwapLargeGuardAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(!(pubkey_eq(&accounts.admin.pubkey, &s.admin_key)));
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !stable_swap_large_guard(
            &mut s,
            &accounts,
            amount_in,
            min_out,
            fee_bps,
            lane,
            input_mint,
            output_mint
        ),
        "stable_swap_large_guard must reject when guard term is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_stable_swap_large_guard_rejects_invalid_2_amount_in_0() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount_in: u128 = kani::any();
    let min_out: u128 = kani::any();
    let fee_bps: u128 = kani::any();
    let lane: u8 = kani::any();
    let input_mint: [u8; 32] = kani::any();
    let output_mint: [u8; 32] = kani::any();
    let accounts = StableSwapLargeGuardAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(pubkey_eq(&accounts.admin.pubkey, &s.admin_key));
    kani::assume(amount_in <= 0);
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !stable_swap_large_guard(
            &mut s,
            &accounts,
            amount_in,
            min_out,
            fee_bps,
            lane,
            input_mint,
            output_mint
        ),
        "stable_swap_large_guard must reject when guard term is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_stable_swap_large_guard_rejects_invalid_3_min_out_0() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount_in: u128 = kani::any();
    let min_out: u128 = kani::any();
    let fee_bps: u128 = kani::any();
    let lane: u8 = kani::any();
    let input_mint: [u8; 32] = kani::any();
    let output_mint: [u8; 32] = kani::any();
    let accounts = StableSwapLargeGuardAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(pubkey_eq(&accounts.admin.pubkey, &s.admin_key));
    kani::assume(amount_in > 0);
    kani::assume(min_out <= 0);
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !stable_swap_large_guard(
            &mut s,
            &accounts,
            amount_in,
            min_out,
            fee_bps,
            lane,
            input_mint,
            output_mint
        ),
        "stable_swap_large_guard must reject when guard term is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_stable_swap_large_guard_rejects_invalid_4_fee_bps_10000() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount_in: u128 = kani::any();
    let min_out: u128 = kani::any();
    let fee_bps: u128 = kani::any();
    let lane: u8 = kani::any();
    let input_mint: [u8; 32] = kani::any();
    let output_mint: [u8; 32] = kani::any();
    let accounts = StableSwapLargeGuardAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(pubkey_eq(&accounts.admin.pubkey, &s.admin_key));
    kani::assume(amount_in > 0);
    kani::assume(min_out > 0);
    kani::assume(fee_bps > 10000);
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !stable_swap_large_guard(
            &mut s,
            &accounts,
            amount_in,
            min_out,
            fee_bps,
            lane,
            input_mint,
            output_mint
        ),
        "stable_swap_large_guard must reject when guard term is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_stable_swap_large_guard_rejects_invalid_5_lane_32() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount_in: u128 = kani::any();
    let min_out: u128 = kani::any();
    let fee_bps: u128 = kani::any();
    let lane: u8 = kani::any();
    let input_mint: [u8; 32] = kani::any();
    let output_mint: [u8; 32] = kani::any();
    let accounts = StableSwapLargeGuardAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(pubkey_eq(&accounts.admin.pubkey, &s.admin_key));
    kani::assume(amount_in > 0);
    kani::assume(min_out > 0);
    kani::assume(fee_bps <= 10000);
    kani::assume(lane >= 32);
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !stable_swap_large_guard(
            &mut s,
            &accounts,
            amount_in,
            min_out,
            fee_bps,
            lane,
            input_mint,
            output_mint
        ),
        "stable_swap_large_guard must reject when guard term is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_stable_swap_large_guard_rejects_invalid_6_pubkey_ne_input_mint_output_mint() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount_in: u128 = kani::any();
    let min_out: u128 = kani::any();
    let fee_bps: u128 = kani::any();
    let lane: u8 = kani::any();
    let input_mint: [u8; 32] = kani::any();
    let output_mint: [u8; 32] = kani::any();
    let accounts = StableSwapLargeGuardAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(pubkey_eq(&accounts.admin.pubkey, &s.admin_key));
    kani::assume(amount_in > 0);
    kani::assume(min_out > 0);
    kani::assume(fee_bps <= 10000);
    kani::assume(lane < 32);
    kani::assume(!(pubkey_ne(&input_mint, &output_mint)));
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !stable_swap_large_guard(
            &mut s,
            &accounts,
            amount_in,
            min_out,
            fee_bps,
            lane,
            input_mint,
            output_mint
        ),
        "stable_swap_large_guard must reject when guard term is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_stable_swap_large_guard_rejects_invalid_7_pubkey_eq_input_mint_output_mint_amount_in_min_out(
) {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount_in: u128 = kani::any();
    let min_out: u128 = kani::any();
    let fee_bps: u128 = kani::any();
    let lane: u8 = kani::any();
    let input_mint: [u8; 32] = kani::any();
    let output_mint: [u8; 32] = kani::any();
    let accounts = StableSwapLargeGuardAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(pubkey_eq(&accounts.admin.pubkey, &s.admin_key));
    kani::assume(amount_in > 0);
    kani::assume(min_out > 0);
    kani::assume(fee_bps <= 10000);
    kani::assume(lane < 32);
    kani::assume(pubkey_ne(&input_mint, &output_mint));
    kani::assume(!(pubkey_eq(&input_mint, &output_mint) || amount_in >= min_out));
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !stable_swap_large_guard(
            &mut s,
            &accounts,
            amount_in,
            min_out,
            fee_bps,
            lane,
            input_mint,
            output_mint
        ),
        "stable_swap_large_guard must reject when guard term is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_stable_swap_large_guard_rejects_invalid_8_mul_bps_floor_u128_amount_in_fee_bps_amount_in()
{
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount_in: u128 = kani::any();
    let min_out: u128 = kani::any();
    let fee_bps: u128 = kani::any();
    let lane: u8 = kani::any();
    let input_mint: [u8; 32] = kani::any();
    let output_mint: [u8; 32] = kani::any();
    let accounts = StableSwapLargeGuardAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(pubkey_eq(&accounts.admin.pubkey, &s.admin_key));
    kani::assume(amount_in > 0);
    kani::assume(min_out > 0);
    kani::assume(fee_bps <= 10000);
    kani::assume(lane < 32);
    kani::assume(pubkey_ne(&input_mint, &output_mint));
    kani::assume((pubkey_eq(&input_mint, &output_mint) || amount_in >= min_out));
    let __qed_bps_floor_1 = mul_bps_floor_u128(amount_in, fee_bps);
    kani::assume(__qed_bps_floor_1 > amount_in);
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !stable_swap_large_guard(
            &mut s,
            &accounts,
            amount_in,
            min_out,
            fee_bps,
            lane,
            input_mint,
            output_mint
        ),
        "stable_swap_large_guard must reject when guard term is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_stable_swap_large_guard_rejects_invalid_9_amount_in_min_out() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount_in: u128 = kani::any();
    let min_out: u128 = kani::any();
    let fee_bps: u128 = kani::any();
    let lane: u8 = kani::any();
    let input_mint: [u8; 32] = kani::any();
    let output_mint: [u8; 32] = kani::any();
    let accounts = StableSwapLargeGuardAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(pubkey_eq(&accounts.admin.pubkey, &s.admin_key));
    kani::assume(amount_in > 0);
    kani::assume(min_out > 0);
    kani::assume(fee_bps <= 10000);
    kani::assume(lane < 32);
    kani::assume(pubkey_ne(&input_mint, &output_mint));
    kani::assume((pubkey_eq(&input_mint, &output_mint) || amount_in >= min_out));
    let __qed_bps_floor_1 = mul_bps_floor_u128(amount_in, fee_bps);
    kani::assume(__qed_bps_floor_1 <= amount_in);
    kani::assume(amount_in < min_out);
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !stable_swap_large_guard(
            &mut s,
            &accounts,
            amount_in,
            min_out,
            fee_bps,
            lane,
            input_mint,
            output_mint
        ),
        "stable_swap_large_guard must reject when guard term is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_stable_swap_large_guard_rejects_invalid_10_amount_in_1000000000000000() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount_in: u128 = kani::any();
    let min_out: u128 = kani::any();
    let fee_bps: u128 = kani::any();
    let lane: u8 = kani::any();
    let input_mint: [u8; 32] = kani::any();
    let output_mint: [u8; 32] = kani::any();
    let accounts = StableSwapLargeGuardAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(pubkey_eq(&accounts.admin.pubkey, &s.admin_key));
    kani::assume(amount_in > 0);
    kani::assume(min_out > 0);
    kani::assume(fee_bps <= 10000);
    kani::assume(lane < 32);
    kani::assume(pubkey_ne(&input_mint, &output_mint));
    kani::assume((pubkey_eq(&input_mint, &output_mint) || amount_in >= min_out));
    let __qed_bps_floor_1 = mul_bps_floor_u128(amount_in, fee_bps);
    kani::assume(__qed_bps_floor_1 <= amount_in);
    kani::assume(amount_in >= min_out);
    kani::assume(amount_in > 1000000000000000);
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !stable_swap_large_guard(
            &mut s,
            &accounts,
            amount_in,
            min_out,
            fee_bps,
            lane,
            input_mint,
            output_mint
        ),
        "stable_swap_large_guard must reject when guard term is violated"
    );
}

// ============================================================================
// Ensures preservation — `ensures <expr>` clauses verified against
// (pre, post) of the spec-translated transition. Counterexamples here
// indicate the spec's effect block doesn't satisfy its own ensures —
// usually because the math lives in the user's Rust impl, behind a
// `modifies`-driven todo!() fill site. See SKILL.md §ref_impl.
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_unbound_transfer_ensures_0() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    let accounts = UnboundTransferAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(pubkey_eq(&accounts.admin.pubkey, &s.admin_key) && amount > 0);
    let pre = s.clone();
    if unbound_transfer(&mut s, &accounts, amount) {
        let post = &s;
        // CPI ensures-as-fact (Token.transfer):
        // `Token.transfer` ensures skipped: missing `state_binders` for from_balance.
        // `Token.transfer` ensures skipped: missing `state_binders` for to_balance.
        assert!(
            post.pool_balance == pre.pool_balance,
            "ensures clause 0 on unbound_transfer violated by spec-translated transition"
        );
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_bound_transfer_ensures_0() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    let accounts = BoundTransferAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(pubkey_eq(&accounts.admin.pubkey, &s.admin_key) && amount > 0);
    let pre = s.clone();
    if bound_transfer(&mut s, &accounts, amount) {
        let post = &s;
        // CPI ensures-as-fact (Token.transfer):
        kani::assume(post.pool_balance == pre.pool_balance - amount);
        kani::assume(post.user_balance == pre.user_balance + amount);
        assert!(
            ((post.pool_balance) as u128) + ((amount) as u128) == ((pre.pool_balance) as u128),
            "ensures clause 0 on bound_transfer violated by spec-translated transition"
        );
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_stable_swap_large_guard_ensures_0() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount_in: u128 = kani::any();
    let min_out: u128 = kani::any();
    let fee_bps: u128 = kani::any();
    let lane: u8 = kani::any();
    let input_mint: [u8; 32] = kani::any();
    let output_mint: [u8; 32] = kani::any();
    let accounts = StableSwapLargeGuardAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(
        pubkey_eq(&accounts.admin.pubkey, &s.admin_key)
            && amount_in > 0
            && min_out > 0
            && fee_bps <= 10000
            && lane < 32
            && pubkey_ne(&input_mint, &output_mint)
            && (pubkey_eq(&input_mint, &output_mint) || amount_in >= min_out)
            && mul_bps_floor_u128(amount_in, fee_bps) <= amount_in
            && amount_in >= min_out
            && amount_in <= 1000000000000000,
    );
    let pre = s.clone();
    if stable_swap_large_guard(
        &mut s,
        &accounts,
        amount_in,
        min_out,
        fee_bps,
        lane,
        input_mint,
        output_mint,
    ) {
        let post = &s;
        assert!(
            post.pool_balance == pre.pool_balance,
            "ensures clause 0 on stable_swap_large_guard violated by spec-translated transition"
        );
    }
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_effect_admin_key() {
    let mut s = State {
        admin_key: [0u8; 32],
        pool_balance: 0,
        user_balance: 0,
        status: Status::Uninitialized,
    };
    let pre_pool_balance = s.pool_balance;
    let pre_user_balance = s.user_balance;
    let accounts = InitializeAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
    };
    if initialize(&mut s, &accounts) {
        assert!(
            pubkey_eq(&s.admin_key, &accounts.admin.pubkey),
            "admin_key must equal accounts.admin.pubkey"
        );
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_effect_pool_balance() {
    let mut s = State {
        admin_key: [0u8; 32],
        pool_balance: 0,
        user_balance: 0,
        status: Status::Uninitialized,
    };
    let pre_admin_key = s.admin_key;
    let pre_user_balance = s.user_balance;
    let accounts = InitializeAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
    };
    if initialize(&mut s, &accounts) {
        assert!(s.pool_balance == 0, "pool_balance must equal 0");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_effect_user_balance() {
    let mut s = State {
        admin_key: [0u8; 32],
        pool_balance: 0,
        user_balance: 0,
        status: Status::Uninitialized,
    };
    let pre_admin_key = s.admin_key;
    let pre_pool_balance = s.pool_balance;
    let accounts = InitializeAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
    };
    if initialize(&mut s, &accounts) {
        assert!(s.user_balance == 0, "user_balance must equal 0");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_bound_transfer_effect_pool_balance() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    let pre_admin_key = s.admin_key;
    let pre_pool_balance = s.pool_balance;
    let pre_user_balance = s.user_balance;
    let accounts = BoundTransferAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    if bound_transfer(&mut s, &accounts, amount) {
        assert!(
            s.pool_balance == pre_pool_balance.wrapping_sub(amount),
            "pool_balance must decrement by amount"
        );
        assert!(
            pubkey_eq(&s.admin_key, &pre_admin_key),
            "admin_key must not change"
        );
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_bound_transfer_effect_user_balance() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    let pre_admin_key = s.admin_key;
    let pre_pool_balance = s.pool_balance;
    let pre_user_balance = s.user_balance;
    let accounts = BoundTransferAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    if bound_transfer(&mut s, &accounts, amount) {
        assert!(
            s.user_balance == pre_user_balance.wrapping_add(amount),
            "user_balance must increment by amount"
        );
        assert!(
            pubkey_eq(&s.admin_key, &pre_admin_key),
            "admin_key must not change"
        );
    }
}

// ============================================================================
// Overflow detection — Kani catches arithmetic overflow on add effects
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_bound_transfer_no_overflow() {
    let mut s = State {
        admin_key: kani::any(),
        pool_balance: kani::any(),
        user_balance: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    let accounts = BoundTransferAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        pool_ta: KaniAccount {
            pubkey: kani::any(),
        },
        user_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    bound_transfer(&mut s, &accounts, amount); // Kani detects overflow on += internally
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
