// ---- GENERATED BY QEDGEN — DO NOT EDIT ----
//! v2.29 Slice H mirror of `AdminConfig`'s account types
//! (sourced from dep `admin_config`).
//!
//! Hand-editing is unsafe: every `qedgen codegen` regenerates
//! this file from the imported `.qedspec`'s `type` declarations.
//! To change a field, change the imported spec and re-resolve.

use anchor_lang::prelude::*;

#[account]
pub struct State {
    pub admin: Pubkey,
    pub pause_authority: Pubkey,
    pub status: u8,
}

/// State lifecycle states (mirrored from `admin_config`).
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum StateStatus {
    Active = 0,
}

// ---- END GENERATED ----
