// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:ca60d0709ea2a161
use quasar_lang::prelude::*;

#[event(discriminator = 1)]
pub struct PoolInitialized {
    pub authority: Pubkey,
    pub rate: u64,
}

#[event(discriminator = 2)]
pub struct Deposited {
    pub depositor: Pubkey,
    pub amount: u64,
}

#[event(discriminator = 3)]
pub struct Borrowed {
    pub borrower: Pubkey,
    pub amount: u64,
}

#[event(discriminator = 4)]
pub struct Repaid {
    pub borrower: Pubkey,
    pub amount: u64,
}

#[event(discriminator = 5)]
pub struct LoanLiquidated {
    pub borrower: Pubkey,
    pub amount: u64,
}

// ---- END GENERATED ----
