// ---- GENERATED BY QEDGEN — DO NOT EDIT — regenerated from .qedspec ----
//! Per-handler guard checks derived from the `.qedspec`.
//! Called from user-owned `instructions/<name>::handler` before
//! business logic; keep guard logic here, policy-free logic there.

#![allow(unused_variables, unused_imports, dead_code, clippy::too_many_arguments)]

use quasar_lang::prelude::*;
use crate::errors::*;
use crate::state::*;
use crate::instructions::*;

/// Guards for `init_pool`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn init_pool<'info>(ctx: &mut InitPool<'info>, rate: u64) -> Result<(), ProgramError> {
    // requires: rate > 0
    if !(rate > 0) { return Err(ProgramError::from(LendingError::InvalidAmount)); }
    // lifecycle: status := Active
    ctx.pool.status = PoolStatus::Active as u8;
    Ok(())
}

/// Guards for `deposit`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn deposit<'info>(ctx: &mut Deposit<'info>, amount: u64) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.pool.status != PoolStatus::Active as u8 { return Err(ProgramError::from(crate::errors::LendingError::InvalidLifecycle)); }
    // R28 PDA check: ctx.pool matches its declared seeds
    {
        let __seeds: &[&[u8]] = &[b"pool", ctx.pool.authority.as_ref(), &[ctx.pool.bump]];
        if quasar_lang::pda::verify_program_address(__seeds, &crate::ID, ctx.pool.to_account_view().address()).is_err() {
            return Err(ProgramError::from(LendingError::InvalidPda));
        }
    }
    // authority: (*ctx.pool_vault.owner()) != (*ctx.pool.to_account_view().address())
    if (*ctx.pool_vault.owner()) != (*ctx.pool.to_account_view().address()) { return Err(ProgramError::from(LendingError::Unauthorized)); }
    // requires: amount > 0
    if !(amount > 0) { return Err(ProgramError::from(LendingError::InvalidAmount)); }
    Ok(())
}

/// Guards for `borrow`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn borrow<'info>(ctx: &mut Borrow<'info>, amount: u64, collateral: u64) -> Result<(), ProgramError> {
    // R28 PDA check: ctx.pool matches its declared seeds
    {
        let __seeds: &[&[u8]] = &[b"pool", ctx.pool.authority.as_ref(), &[ctx.pool.bump]];
        if quasar_lang::pda::verify_program_address(__seeds, &crate::ID, ctx.pool.to_account_view().address()).is_err() {
            return Err(ProgramError::from(LendingError::InvalidPda));
        }
    }
    // authority: (*ctx.pool_vault.owner()) != (*ctx.pool.to_account_view().address())
    if (*ctx.pool_vault.owner()) != (*ctx.pool.to_account_view().address()) { return Err(ProgramError::from(LendingError::Unauthorized)); }
    // requires: amount > 0 ∧ collateral > 0
    if !((amount > 0) && (collateral > 0)) { return Err(ProgramError::from(LendingError::InvalidAmount)); }
    // lifecycle: status := Active
    ctx.loan.status = LoanStatus::Active as u8;
    Ok(())
}

/// Guards for `repay`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn repay<'info>(ctx: &mut Repay<'info>) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.loan.status != LoanStatus::Active as u8 { return Err(ProgramError::from(crate::errors::LendingError::InvalidLifecycle)); }
    // R28 PDA check: ctx.pool matches its declared seeds
    {
        let __seeds: &[&[u8]] = &[b"pool", ctx.pool.authority.as_ref(), &[ctx.pool.bump]];
        if quasar_lang::pda::verify_program_address(__seeds, &crate::ID, ctx.pool.to_account_view().address()).is_err() {
            return Err(ProgramError::from(LendingError::InvalidPda));
        }
    }
    // authority: (*ctx.pool_vault.owner()) != (*ctx.pool.to_account_view().address())
    if (*ctx.pool_vault.owner()) != (*ctx.pool.to_account_view().address()) { return Err(ProgramError::from(LendingError::Unauthorized)); }
    // lifecycle: status := Empty
    ctx.loan.status = LoanStatus::Empty as u8;
    Ok(())
}

/// Guards for `liquidate`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn liquidate<'info>(ctx: &mut Liquidate<'info>) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.loan.status != LoanStatus::Active as u8 { return Err(ProgramError::from(crate::errors::LendingError::InvalidLifecycle)); }
    // R28 PDA check: ctx.loan matches its declared seeds
    {
        let __seeds: &[&[u8]] = &[b"loan", ctx.pool.to_account_view().address().as_ref(), ctx.loan.borrower.as_ref(), &[ctx.loan.bump]];
        if quasar_lang::pda::verify_program_address(__seeds, &crate::ID, ctx.loan.to_account_view().address()).is_err() {
            return Err(ProgramError::from(LendingError::InvalidPda));
        }
    }
    // R28 PDA check: ctx.pool matches its declared seeds
    {
        let __seeds: &[&[u8]] = &[b"pool", ctx.pool.authority.as_ref(), &[ctx.pool.bump]];
        if quasar_lang::pda::verify_program_address(__seeds, &crate::ID, ctx.pool.to_account_view().address()).is_err() {
            return Err(ProgramError::from(LendingError::InvalidPda));
        }
    }
    // authority: (*ctx.pool_vault.owner()) != (*ctx.pool.to_account_view().address())
    if (*ctx.pool_vault.owner()) != (*ctx.pool.to_account_view().address()) { return Err(ProgramError::from(LendingError::Unauthorized)); }
    // requires: s.amount > s.collateral
    if !(ctx.loan.amount.get() > ctx.loan.collateral.get()) { return Err(ProgramError::from(LendingError::AccountHealthy)); }
    // lifecycle: status := Liquidated
    ctx.loan.status = LoanStatus::Liquidated as u8;
    Ok(())
}

// ---- END GENERATED ----
