// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:347edefe956d3674
#![allow(unexpected_cfgs)]
#![cfg_attr(any(target_os = "solana", target_arch = "bpf"), no_std)]

use quasar_lang::prelude::*;

mod instructions;
use instructions::*;
pub mod events;
pub mod errors;
pub mod state;
pub mod guards;

declare_id!("11111111111111111111111111111111");

#[program]
mod lending {
    use super::*;

    #[instruction(discriminator = 0)]
    pub fn init_pool(ctx: Ctx<InitPool>, rate: u64) -> Result<(), ProgramError> {
        ctx.accounts.handler(rate, &ctx.bumps)
    }

    #[instruction(discriminator = 1)]
    pub fn deposit(ctx: Ctx<Deposit>, amount: u64) -> Result<(), ProgramError> {
        ctx.accounts.handler(amount, &ctx.bumps)
    }

    #[instruction(discriminator = 2)]
    pub fn borrow(ctx: Ctx<Borrow>, amount: u64, collateral: u64) -> Result<(), ProgramError> {
        ctx.accounts.handler(amount, collateral, &ctx.bumps)
    }

    #[instruction(discriminator = 3)]
    pub fn repay(ctx: Ctx<Repay>) -> Result<(), ProgramError> {
        ctx.accounts.handler(&ctx.bumps)
    }

    #[instruction(discriminator = 4)]
    pub fn liquidate(ctx: Ctx<Liquidate>) -> Result<(), ProgramError> {
        ctx.accounts.handler(&ctx.bumps)
    }

}
// ---- END GENERATED ----
