// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:9789d5b48c9c2ac9
use quasar_lang::prelude::*;

#[account(discriminator = 1)]
pub struct PoolAccount {
    pub authority: Pubkey,
    pub total_deposits: u64,
    pub total_borrows: u64,
    pub interest_rate: u64,
    pub bump: u8,
    pub status: u8,
}

/// Pool lifecycle states.
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum PoolStatus {
    Uninitialized = 0,
    Active = 1,
    Paused = 2,
}

#[account(discriminator = 2)]
pub struct LoanAccount {
    pub borrower: Pubkey,
    pub pool: Pubkey,
    pub amount: u64,
    pub collateral: u64,
    pub bump: u8,
    pub status: u8,
}

/// Loan lifecycle states.
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum LoanStatus {
    Empty = 0,
    Active = 1,
    Liquidated = 2,
}

// ---- END GENERATED ----
