// ---- GENERATED BY QEDGEN ---- spec-hash:4a5ba81b422f88d8
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

const MAX_MEMBERS: u8 = 32;

#[derive(Clone, Copy, PartialEq, Eq, kani::Arbitrary)]
enum Status {
    Uninitialized,
    Active,
    HasProposal,
}

#[derive(Clone, Copy)]
struct State {
    creator: [u8; 32],
    threshold: u8,
    member_count: u8,
    members: [[u8; 32]; 32],
    voted: [u8; 32],
    approval_count: u8,
    rejection_count: u8,
    status: Status,
}

// ============================================================================
// Property predicates (from qedspec `property` declarations)
// ============================================================================

/// threshold_bounded: s.threshold ≤ s.member_count ∧ s.threshold > 0
fn threshold_bounded(s: &State) -> bool {
    (s.threshold <= s.member_count) && (s.threshold > 0)
}

/// votes_bounded: s.approval_count + s.rejection_count ≤ s.member_count
fn votes_bounded(s: &State) -> bool {
    s.approval_count + s.rejection_count <= s.member_count
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn create_vault(s: &mut State, threshold: u8, member_count: u8) -> bool {
    if !(((threshold > 0) && (threshold <= member_count)) && (member_count <= 32)) {
        return false;
    }
    if s.status != Status::Uninitialized {
        return false;
    }
    s.threshold = threshold;
    s.member_count = member_count;
    s.approval_count = 0;
    s.rejection_count = 0;
    s.status = Status::Active;
    true
}

fn propose(s: &mut State) -> bool {
    if s.status != Status::Active {
        return false;
    }
    s.approval_count = 0;
    s.rejection_count = 0;
    s.status = Status::HasProposal;
    true
}

fn approve(s: &mut State, member_index: u8) -> bool {
    if !((member_index < s.member_count) && (s.members[(member_index) as usize] == approver) && (s.voted[(member_index) as usize] == 0)) {
        return false;
    }
    if s.status != Status::HasProposal {
        return false;
    }
    match s.approval_count.checked_add(1) {
        Some(__v) => s.approval_count = __v,
        None => return false,
    }
    s.voted[member_index] = 1;
    s.status = Status::HasProposal;
    true
}

fn reject(s: &mut State, member_index: u8) -> bool {
    if !((member_index < s.member_count) && (s.members[(member_index) as usize] == rejecter) && (s.voted[(member_index) as usize] == 0)) {
        return false;
    }
    if s.status != Status::HasProposal {
        return false;
    }
    match s.rejection_count.checked_add(1) {
        Some(__v) => s.rejection_count = __v,
        None => return false,
    }
    s.voted[member_index] = 1;
    s.status = Status::HasProposal;
    true
}

fn execute(s: &mut State, member_index: u8) -> bool {
    if !((member_index < s.member_count) && (s.members[(member_index) as usize] == executor) && (s.approval_count >= s.threshold)) {
        return false;
    }
    if s.status != Status::HasProposal {
        return false;
    }
    s.approval_count = 0;
    s.rejection_count = 0;
    s.status = Status::Active;
    true
}

fn cancel_proposal(s: &mut State) -> bool {
    if !((s.member_count - s.rejection_count < s.threshold)) {
        return false;
    }
    if s.status != Status::HasProposal {
        return false;
    }
    s.approval_count = 0;
    s.rejection_count = 0;
    s.status = Status::Active;
    true
}

fn add_member(s: &mut State, member_index: u8, member_pubkey: [u8; 32]) -> bool {
    if !((member_index < s.member_count)) {
        return false;
    }
    if s.status != Status::Active {
        return false;
    }
    s.members[member_index] = member_pubkey;
    s.status = Status::Active;
    true
}

fn remove_member(s: &mut State) -> bool {
    if !((s.member_count > s.threshold) && ((s.approval_count == 0) && (s.rejection_count == 0))) {
        return false;
    }
    if s.status != Status::Active {
        return false;
    }
    match s.member_count.checked_sub(1) {
        Some(__v) => s.member_count = __v,
        None => return false,
    }
    s.status = Status::Active;
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_rejects_invalid() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Uninitialized);
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    kani::assume(!(((threshold > 0) && (threshold <= member_count)) && (member_count <= 32)));
    assert!(!create_vault(&mut s, threshold, member_count),
        "create_vault must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_rejects_invalid() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    let member_index: u8 = kani::any();
    kani::assume(!((member_index < s.member_count) && (s.members[(member_index) as usize] == approver) && (s.voted[(member_index) as usize] == 0)));
    assert!(!approve(&mut s, member_index),
        "approve must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_reject_rejects_invalid() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    let member_index: u8 = kani::any();
    kani::assume(!((member_index < s.member_count) && (s.members[(member_index) as usize] == rejecter) && (s.voted[(member_index) as usize] == 0)));
    assert!(!reject(&mut s, member_index),
        "reject must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_execute_rejects_invalid() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    let member_index: u8 = kani::any();
    kani::assume(!((member_index < s.member_count) && (s.members[(member_index) as usize] == executor) && (s.approval_count >= s.threshold)));
    assert!(!execute(&mut s, member_index),
        "execute must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_cancel_proposal_rejects_invalid() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    kani::assume(!((s.member_count - s.rejection_count < s.threshold)));
    assert!(!cancel_proposal(&mut s),
        "cancel_proposal must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_add_member_rejects_invalid() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let member_index: u8 = kani::any();
    let member_pubkey: [u8; 32] = kani::any();
    kani::assume(!((member_index < s.member_count)));
    assert!(!add_member(&mut s, member_index, member_pubkey),
        "add_member must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_remove_member_rejects_invalid() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    kani::assume(!((s.member_count > s.threshold) && ((s.approval_count == 0) && (s.rejection_count == 0))));
    assert!(!remove_member(&mut s),
        "remove_member must reject when guard is violated");
}

// ============================================================================
// Property preservation — invariants hold through all transitions
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_preserves_threshold_bounded() {
    let mut s = State {
        creator: 0,
        threshold: 0,
        member_count: 0,
        members: 0,
        voted: 0,
        approval_count: 0,
        rejection_count: 0,
        status: Status::Uninitialized,
    };
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    if create_vault(&mut s, threshold, member_count) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after create_vault");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_propose_preserves_threshold_bounded() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    kani::assume(threshold_bounded(&s));
    kani::assume(votes_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if propose(&mut s) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after propose");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_preserves_threshold_bounded() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    kani::assume(threshold_bounded(&s));
    kani::assume(votes_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    let member_index: u8 = kani::any();
    if approve(&mut s, member_index) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after approve");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_reject_preserves_threshold_bounded() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    kani::assume(threshold_bounded(&s));
    kani::assume(votes_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    let member_index: u8 = kani::any();
    kani::assume(s.rejection_count < s.member_count); // strict bound: rejection_count increments
    if reject(&mut s, member_index) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after reject");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_execute_preserves_threshold_bounded() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    kani::assume(threshold_bounded(&s));
    kani::assume(votes_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    let member_index: u8 = kani::any();
    if execute(&mut s, member_index) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after execute");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_cancel_proposal_preserves_threshold_bounded() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    kani::assume(threshold_bounded(&s));
    kani::assume(votes_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if cancel_proposal(&mut s) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after cancel_proposal");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_add_member_preserves_threshold_bounded() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    kani::assume(threshold_bounded(&s));
    kani::assume(votes_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    let member_index: u8 = kani::any();
    let member_pubkey: [u8; 32] = kani::any();
    if add_member(&mut s, member_index, member_pubkey) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after add_member");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_remove_member_preserves_threshold_bounded() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    kani::assume(threshold_bounded(&s));
    kani::assume(votes_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if remove_member(&mut s) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after remove_member");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_preserves_votes_bounded() {
    let mut s = State {
        creator: 0,
        threshold: 0,
        member_count: 0,
        members: 0,
        voted: 0,
        approval_count: 0,
        rejection_count: 0,
        status: Status::Uninitialized,
    };
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    if create_vault(&mut s, threshold, member_count) {
        assert!(votes_bounded(&s),
            "votes_bounded must hold after create_vault");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_propose_preserves_votes_bounded() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    kani::assume(threshold_bounded(&s));
    kani::assume(votes_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if propose(&mut s) {
        assert!(votes_bounded(&s),
            "votes_bounded must hold after propose");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_execute_preserves_votes_bounded() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    kani::assume(threshold_bounded(&s));
    kani::assume(votes_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    let member_index: u8 = kani::any();
    if execute(&mut s, member_index) {
        assert!(votes_bounded(&s),
            "votes_bounded must hold after execute");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_cancel_proposal_preserves_votes_bounded() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    kani::assume(threshold_bounded(&s));
    kani::assume(votes_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if cancel_proposal(&mut s) {
        assert!(votes_bounded(&s),
            "votes_bounded must hold after cancel_proposal");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_remove_member_preserves_votes_bounded() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    kani::assume(threshold_bounded(&s));
    kani::assume(votes_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if remove_member(&mut s) {
        assert!(votes_bounded(&s),
            "votes_bounded must hold after remove_member");
    }
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_effect_threshold() {
    let mut s = State {
        creator: 0,
        threshold: 0,
        member_count: 0,
        members: 0,
        voted: 0,
        approval_count: 0,
        rejection_count: 0,
        status: Status::Uninitialized,
    };
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    let pre_creator = s.creator;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_approval_count = s.approval_count;
    let pre_rejection_count = s.rejection_count;
    if create_vault(&mut s, threshold, member_count) {
        assert!(s.threshold == threshold, "threshold must equal threshold");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_effect_member_count() {
    let mut s = State {
        creator: 0,
        threshold: 0,
        member_count: 0,
        members: 0,
        voted: 0,
        approval_count: 0,
        rejection_count: 0,
        status: Status::Uninitialized,
    };
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_approval_count = s.approval_count;
    let pre_rejection_count = s.rejection_count;
    if create_vault(&mut s, threshold, member_count) {
        assert!(s.member_count == member_count, "member_count must equal member_count");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_effect_approval_count() {
    let mut s = State {
        creator: 0,
        threshold: 0,
        member_count: 0,
        members: 0,
        voted: 0,
        approval_count: 0,
        rejection_count: 0,
        status: Status::Uninitialized,
    };
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_rejection_count = s.rejection_count;
    if create_vault(&mut s, threshold, member_count) {
        assert!(s.approval_count == 0, "approval_count must equal 0");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_effect_rejection_count() {
    let mut s = State {
        creator: 0,
        threshold: 0,
        member_count: 0,
        members: 0,
        voted: 0,
        approval_count: 0,
        rejection_count: 0,
        status: Status::Uninitialized,
    };
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_approval_count = s.approval_count;
    if create_vault(&mut s, threshold, member_count) {
        assert!(s.rejection_count == 0, "rejection_count must equal 0");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_propose_effect_approval_count() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_rejection_count = s.rejection_count;
    if propose(&mut s) {
        assert!(s.approval_count == 0, "approval_count must equal 0");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_propose_effect_rejection_count() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_approval_count = s.approval_count;
    if propose(&mut s) {
        assert!(s.rejection_count == 0, "rejection_count must equal 0");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_effect_approval_count() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    let member_index: u8 = kani::any();
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_approval_count = s.approval_count;
    let pre_rejection_count = s.rejection_count;
    if approve(&mut s, member_index) {
        assert!(s.approval_count == pre_approval_count.wrapping_add(1), "approval_count must increment by 1");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
        assert!(s.rejection_count == pre_rejection_count, "rejection_count must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_effect_voted_member_index() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    let member_index: u8 = kani::any();
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_approval_count = s.approval_count;
    let pre_rejection_count = s.rejection_count;
    if approve(&mut s, member_index) {
        assert!(s.voted[member_index] == 1, "voted[member_index] must equal 1");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
        assert!(s.rejection_count == pre_rejection_count, "rejection_count must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_reject_effect_rejection_count() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    let member_index: u8 = kani::any();
    kani::assume(s.member_count <= MAX_MEMBERS);
    kani::assume(s.rejection_count < s.member_count); // strict bound: rejection_count increments
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_approval_count = s.approval_count;
    let pre_rejection_count = s.rejection_count;
    if reject(&mut s, member_index) {
        assert!(s.rejection_count == pre_rejection_count.wrapping_add(1), "rejection_count must increment by 1");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
        assert!(s.approval_count == pre_approval_count, "approval_count must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_reject_effect_voted_member_index() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    let member_index: u8 = kani::any();
    kani::assume(s.member_count <= MAX_MEMBERS);
    kani::assume(s.rejection_count < s.member_count); // strict bound: rejection_count increments
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_approval_count = s.approval_count;
    let pre_rejection_count = s.rejection_count;
    if reject(&mut s, member_index) {
        assert!(s.voted[member_index] == 1, "voted[member_index] must equal 1");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
        assert!(s.approval_count == pre_approval_count, "approval_count must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_execute_effect_approval_count() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    let member_index: u8 = kani::any();
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_rejection_count = s.rejection_count;
    if execute(&mut s, member_index) {
        assert!(s.approval_count == 0, "approval_count must equal 0");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_execute_effect_rejection_count() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    let member_index: u8 = kani::any();
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_approval_count = s.approval_count;
    if execute(&mut s, member_index) {
        assert!(s.rejection_count == 0, "rejection_count must equal 0");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_cancel_proposal_effect_approval_count() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_rejection_count = s.rejection_count;
    if cancel_proposal(&mut s) {
        assert!(s.approval_count == 0, "approval_count must equal 0");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_cancel_proposal_effect_rejection_count() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_approval_count = s.approval_count;
    if cancel_proposal(&mut s) {
        assert!(s.rejection_count == 0, "rejection_count must equal 0");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_add_member_effect_members_member_index() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let member_index: u8 = kani::any();
    let member_pubkey: [u8; 32] = kani::any();
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_approval_count = s.approval_count;
    let pre_rejection_count = s.rejection_count;
    if add_member(&mut s, member_index, member_pubkey) {
        assert!(s.members[member_index] == member_pubkey, "members[member_index] must equal member_pubkey");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
        assert!(s.approval_count == pre_approval_count, "approval_count must not change");
        assert!(s.rejection_count == pre_rejection_count, "rejection_count must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_remove_member_effect_member_count() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_creator = s.creator;
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_members = s.members;
    let pre_voted = s.voted;
    let pre_approval_count = s.approval_count;
    let pre_rejection_count = s.rejection_count;
    if remove_member(&mut s) {
        assert!(s.member_count == pre_member_count.wrapping_sub(1), "member_count must decrement by 1");
        assert!(s.creator == pre_creator, "creator must not change");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.members == pre_members, "members must not change");
        assert!(s.voted == pre_voted, "voted must not change");
        assert!(s.approval_count == pre_approval_count, "approval_count must not change");
        assert!(s.rejection_count == pre_rejection_count, "rejection_count must not change");
    }
}

// ============================================================================
// Overflow detection — Kani catches arithmetic overflow on add effects
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_no_overflow() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    let member_index: u8 = kani::any();
    approve(&mut s, member_index);  // Kani detects overflow on += internally
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_reject_no_overflow() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    let member_index: u8 = kani::any();
    reject(&mut s, member_index);  // Kani detects overflow on += internally
}

// ============================================================================
// Cover properties — reachability via kani::cover!
// ============================================================================

#[kani::proof]
#[kani::unwind(5)]
#[kani::solver(cadical)]
fn cover_proposal_lifecycle() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    let threshold_0: u8 = kani::any();
    let member_count_0: u8 = kani::any();
    if create_vault(&mut s, threshold_0, member_count_0) {
        if propose(&mut s) {
            let member_index_2: u8 = kani::any();
            if approve(&mut s, member_index_2) {
                let member_index_3: u8 = kani::any();
                kani::cover!(execute(&mut s, member_index_3), "proposal_lifecycle trace is reachable");
            }
        }
    }
}

#[kani::proof]
#[kani::unwind(5)]
#[kani::solver(cadical)]
fn cover_rejection_flow() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    let threshold_0: u8 = kani::any();
    let member_count_0: u8 = kani::any();
    if create_vault(&mut s, threshold_0, member_count_0) {
        if propose(&mut s) {
            let member_index_2: u8 = kani::any();
            if reject(&mut s, member_index_2) {
                kani::cover!(cancel_proposal(&mut s), "rejection_flow trace is reachable");
            }
        }
    }
}

// ============================================================================
// Liveness properties — bounded reachability via non-deterministic ops
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_liveness_proposal_resolves() {
    let mut s = State {
        creator: kani::any(),
        threshold: kani::any(),
        member_count: kani::any(),
        members: kani::any(),
        voted: kani::any(),
        approval_count: kani::any(),
        rejection_count: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::HasProposal);
    for _ in 0..1 {
        let op: u8 = kani::any();
        match op {
            0 => {
            let member_index: u8 = kani::any();
                execute(&mut s, member_index);
            }
            1 => {
                cancel_proposal(&mut s);
            }
            _ => {}
        }
    }
    kani::cover!(s.status == Status::Active, "proposal_resolves reaches Active within 1 steps");
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
