// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:b85b5fe35f354c17
use quasar_lang::prelude::*;

#[account(discriminator = 1)]
pub struct MultisigAccount {
    pub creator: Pubkey,
    pub threshold: u8,
    pub member_count: u8,
    pub members: [Pubkey; 32],
    pub voted: [u8; 32],
    pub approval_count: u8,
    pub rejection_count: u8,
    pub bump: u8,
    pub status: u8,
}

/// Program lifecycle states.
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Status {
    Uninitialized = 0,
    Active = 1,
    HasProposal = 2,
}
// ---- END GENERATED ----
