// ---- GENERATED BY QEDGEN ---- spec-hash:6905d903db8f6b15
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

#[allow(dead_code)]
fn pubkey_eq(a: &[u8; 32], b: &[u8; 32]) -> bool {
    a[0] == b[0]
        && a[1] == b[1]
        && a[2] == b[2]
        && a[3] == b[3]
        && a[4] == b[4]
        && a[5] == b[5]
        && a[6] == b[6]
        && a[7] == b[7]
        && a[8] == b[8]
        && a[9] == b[9]
        && a[10] == b[10]
        && a[11] == b[11]
        && a[12] == b[12]
        && a[13] == b[13]
        && a[14] == b[14]
        && a[15] == b[15]
        && a[16] == b[16]
        && a[17] == b[17]
        && a[18] == b[18]
        && a[19] == b[19]
        && a[20] == b[20]
        && a[21] == b[21]
        && a[22] == b[22]
        && a[23] == b[23]
        && a[24] == b[24]
        && a[25] == b[25]
        && a[26] == b[26]
        && a[27] == b[27]
        && a[28] == b[28]
        && a[29] == b[29]
        && a[30] == b[30]
        && a[31] == b[31]
}

#[allow(dead_code)]
fn pubkey_ne(a: &[u8; 32], b: &[u8; 32]) -> bool {
    !pubkey_eq(a, b)
}

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

#[derive(Clone, Copy, PartialEq, Eq, kani::Arbitrary)]
enum Status {
    Uninitialized,
    Open,
    Closed,
}

#[derive(Clone, Copy)]
struct State {
    initializer: [u8; 32],
    initializer_token_account: [u8; 32],
    taker: [u8; 32],
    initializer_amount: u64,
    taker_amount: u64,
    escrow_token_account: [u8; 32],
    status: Status,
}

#[derive(Clone, Copy)]
struct KaniAccount {
    pubkey: [u8; 32],
}

#[derive(Clone, Copy)]
struct InitializeAccounts {
    initializer: KaniAccount,
    escrow: KaniAccount,
    mint: KaniAccount,
    initializer_ta: KaniAccount,
    escrow_ta: KaniAccount,
    token_program: KaniAccount,
    system_program: KaniAccount,
}

#[derive(Clone, Copy)]
struct ExchangeAccounts {
    taker: KaniAccount,
    escrow: KaniAccount,
    initializer_ta: KaniAccount,
    taker_ta: KaniAccount,
    escrow_ta: KaniAccount,
    token_program: KaniAccount,
}

#[derive(Clone, Copy)]
struct CancelAccounts {
    initializer: KaniAccount,
    escrow: KaniAccount,
    escrow_ta: KaniAccount,
    initializer_ta: KaniAccount,
    token_program: KaniAccount,
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn initialize(
    s: &mut State,
    accounts: &InitializeAccounts,
    deposit_amount: u64,
    receive_amount: u64,
) -> bool {
    if !(deposit_amount > 0 && receive_amount > 0) {
        return false;
    }
    if s.status != Status::Uninitialized {
        return false;
    }
    s.initializer_amount = deposit_amount;
    s.taker_amount = receive_amount;
    s.initializer_token_account = accounts.initializer_ta.pubkey;
    s.status = Status::Open;
    true
}

fn exchange(s: &mut State, accounts: &ExchangeAccounts) -> bool {
    if !(pubkey_eq(
        &accounts.initializer_ta.pubkey,
        &s.initializer_token_account,
    )) {
        return false;
    }
    if s.status != Status::Open {
        return false;
    }
    s.status = Status::Closed;
    true
}

fn cancel(s: &mut State, accounts: &CancelAccounts) -> bool {
    if !(pubkey_eq(
        &accounts.initializer_ta.pubkey,
        &s.initializer_token_account,
    )) {
        return false;
    }
    if s.status != Status::Open {
        return false;
    }
    s.status = Status::Closed;
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_rejects_invalid() {
    let mut s = State {
        initializer: kani::any(),
        initializer_token_account: kani::any(),
        taker: kani::any(),
        initializer_amount: kani::any(),
        taker_amount: kani::any(),
        escrow_token_account: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Uninitialized);
    let deposit_amount: u64 = kani::any();
    let receive_amount: u64 = kani::any();
    let accounts = InitializeAccounts {
        initializer: KaniAccount {
            pubkey: kani::any(),
        },
        escrow: KaniAccount {
            pubkey: kani::any(),
        },
        mint: KaniAccount {
            pubkey: kani::any(),
        },
        initializer_ta: KaniAccount {
            pubkey: kani::any(),
        },
        escrow_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
        system_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(!(deposit_amount > 0 && receive_amount > 0));
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !initialize(&mut s, &accounts, deposit_amount, receive_amount),
        "initialize must reject when guard is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_exchange_rejects_invalid() {
    let mut s = State {
        initializer: kani::any(),
        initializer_token_account: kani::any(),
        taker: kani::any(),
        initializer_amount: kani::any(),
        taker_amount: kani::any(),
        escrow_token_account: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Open);
    let accounts = ExchangeAccounts {
        taker: KaniAccount {
            pubkey: kani::any(),
        },
        escrow: KaniAccount {
            pubkey: kani::any(),
        },
        initializer_ta: KaniAccount {
            pubkey: kani::any(),
        },
        taker_ta: KaniAccount {
            pubkey: kani::any(),
        },
        escrow_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(
        !(pubkey_eq(
            &accounts.initializer_ta.pubkey,
            &s.initializer_token_account,
        )),
    );
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !exchange(&mut s, &accounts),
        "exchange must reject when guard is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_cancel_rejects_invalid() {
    let mut s = State {
        initializer: kani::any(),
        initializer_token_account: kani::any(),
        taker: kani::any(),
        initializer_amount: kani::any(),
        taker_amount: kani::any(),
        escrow_token_account: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Open);
    let accounts = CancelAccounts {
        initializer: KaniAccount {
            pubkey: kani::any(),
        },
        escrow: KaniAccount {
            pubkey: kani::any(),
        },
        escrow_ta: KaniAccount {
            pubkey: kani::any(),
        },
        initializer_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    kani::assume(
        !(pubkey_eq(
            &accounts.initializer_ta.pubkey,
            &s.initializer_token_account,
        )),
    );
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !cancel(&mut s, &accounts),
        "cancel must reject when guard is violated"
    );
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_effect_initializer_amount() {
    let mut s = State {
        initializer: [0u8; 32],
        initializer_token_account: [0u8; 32],
        taker: [0u8; 32],
        initializer_amount: 0,
        taker_amount: 0,
        escrow_token_account: [0u8; 32],
        status: Status::Uninitialized,
    };
    let deposit_amount: u64 = kani::any();
    let receive_amount: u64 = kani::any();
    let pre_initializer = s.initializer;
    let pre_initializer_token_account = s.initializer_token_account;
    let pre_taker = s.taker;
    let pre_taker_amount = s.taker_amount;
    let pre_escrow_token_account = s.escrow_token_account;
    let accounts = InitializeAccounts {
        initializer: KaniAccount {
            pubkey: kani::any(),
        },
        escrow: KaniAccount {
            pubkey: kani::any(),
        },
        mint: KaniAccount {
            pubkey: kani::any(),
        },
        initializer_ta: KaniAccount {
            pubkey: kani::any(),
        },
        escrow_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
        system_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    if initialize(&mut s, &accounts, deposit_amount, receive_amount) {
        assert!(
            s.initializer_amount == deposit_amount,
            "initializer_amount must equal deposit_amount"
        );
        assert!(
            pubkey_eq(&s.initializer, &pre_initializer),
            "initializer must not change"
        );
        assert!(pubkey_eq(&s.taker, &pre_taker), "taker must not change");
        assert!(
            pubkey_eq(&s.escrow_token_account, &pre_escrow_token_account),
            "escrow_token_account must not change"
        );
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_effect_taker_amount() {
    let mut s = State {
        initializer: [0u8; 32],
        initializer_token_account: [0u8; 32],
        taker: [0u8; 32],
        initializer_amount: 0,
        taker_amount: 0,
        escrow_token_account: [0u8; 32],
        status: Status::Uninitialized,
    };
    let deposit_amount: u64 = kani::any();
    let receive_amount: u64 = kani::any();
    let pre_initializer = s.initializer;
    let pre_initializer_token_account = s.initializer_token_account;
    let pre_taker = s.taker;
    let pre_initializer_amount = s.initializer_amount;
    let pre_escrow_token_account = s.escrow_token_account;
    let accounts = InitializeAccounts {
        initializer: KaniAccount {
            pubkey: kani::any(),
        },
        escrow: KaniAccount {
            pubkey: kani::any(),
        },
        mint: KaniAccount {
            pubkey: kani::any(),
        },
        initializer_ta: KaniAccount {
            pubkey: kani::any(),
        },
        escrow_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
        system_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    if initialize(&mut s, &accounts, deposit_amount, receive_amount) {
        assert!(
            s.taker_amount == receive_amount,
            "taker_amount must equal receive_amount"
        );
        assert!(
            pubkey_eq(&s.initializer, &pre_initializer),
            "initializer must not change"
        );
        assert!(pubkey_eq(&s.taker, &pre_taker), "taker must not change");
        assert!(
            pubkey_eq(&s.escrow_token_account, &pre_escrow_token_account),
            "escrow_token_account must not change"
        );
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_effect_initializer_token_account() {
    let mut s = State {
        initializer: [0u8; 32],
        initializer_token_account: [0u8; 32],
        taker: [0u8; 32],
        initializer_amount: 0,
        taker_amount: 0,
        escrow_token_account: [0u8; 32],
        status: Status::Uninitialized,
    };
    let deposit_amount: u64 = kani::any();
    let receive_amount: u64 = kani::any();
    let pre_initializer = s.initializer;
    let pre_taker = s.taker;
    let pre_initializer_amount = s.initializer_amount;
    let pre_taker_amount = s.taker_amount;
    let pre_escrow_token_account = s.escrow_token_account;
    let accounts = InitializeAccounts {
        initializer: KaniAccount {
            pubkey: kani::any(),
        },
        escrow: KaniAccount {
            pubkey: kani::any(),
        },
        mint: KaniAccount {
            pubkey: kani::any(),
        },
        initializer_ta: KaniAccount {
            pubkey: kani::any(),
        },
        escrow_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
        system_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    if initialize(&mut s, &accounts, deposit_amount, receive_amount) {
        assert!(
            pubkey_eq(
                &s.initializer_token_account,
                &accounts.initializer_ta.pubkey
            ),
            "initializer_token_account must equal accounts.initializer_ta.pubkey"
        );
        assert!(
            pubkey_eq(&s.initializer, &pre_initializer),
            "initializer must not change"
        );
        assert!(pubkey_eq(&s.taker, &pre_taker), "taker must not change");
        assert!(
            pubkey_eq(&s.escrow_token_account, &pre_escrow_token_account),
            "escrow_token_account must not change"
        );
    }
}

// ============================================================================
// Cover properties — reachability via kani::cover!
// ============================================================================

#[kani::proof]
#[kani::unwind(3)]
#[kani::solver(cadical)]
fn cover_happy_path() {
    let mut s = State {
        initializer: kani::any(),
        initializer_token_account: kani::any(),
        taker: kani::any(),
        initializer_amount: kani::any(),
        taker_amount: kani::any(),
        escrow_token_account: kani::any(),
        status: kani::any(),
    };
    let deposit_amount_0: u64 = kani::any();
    let receive_amount_0: u64 = kani::any();
    let accounts_0 = InitializeAccounts {
        initializer: KaniAccount {
            pubkey: kani::any(),
        },
        escrow: KaniAccount {
            pubkey: kani::any(),
        },
        mint: KaniAccount {
            pubkey: kani::any(),
        },
        initializer_ta: KaniAccount {
            pubkey: kani::any(),
        },
        escrow_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
        system_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    if initialize(&mut s, &accounts_0, deposit_amount_0, receive_amount_0) {
        let accounts_1 = ExchangeAccounts {
            taker: KaniAccount {
                pubkey: kani::any(),
            },
            escrow: KaniAccount {
                pubkey: kani::any(),
            },
            initializer_ta: KaniAccount {
                pubkey: kani::any(),
            },
            taker_ta: KaniAccount {
                pubkey: kani::any(),
            },
            escrow_ta: KaniAccount {
                pubkey: kani::any(),
            },
            token_program: KaniAccount {
                pubkey: kani::any(),
            },
        };
        kani::cover!(
            exchange(&mut s, &accounts_1),
            "happy_path trace is reachable"
        );
    }
}

#[kani::proof]
#[kani::unwind(3)]
#[kani::solver(cadical)]
fn cover_cancel_path() {
    let mut s = State {
        initializer: kani::any(),
        initializer_token_account: kani::any(),
        taker: kani::any(),
        initializer_amount: kani::any(),
        taker_amount: kani::any(),
        escrow_token_account: kani::any(),
        status: kani::any(),
    };
    let deposit_amount_0: u64 = kani::any();
    let receive_amount_0: u64 = kani::any();
    let accounts_0 = InitializeAccounts {
        initializer: KaniAccount {
            pubkey: kani::any(),
        },
        escrow: KaniAccount {
            pubkey: kani::any(),
        },
        mint: KaniAccount {
            pubkey: kani::any(),
        },
        initializer_ta: KaniAccount {
            pubkey: kani::any(),
        },
        escrow_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
        system_program: KaniAccount {
            pubkey: kani::any(),
        },
    };
    if initialize(&mut s, &accounts_0, deposit_amount_0, receive_amount_0) {
        let accounts_1 = CancelAccounts {
            initializer: KaniAccount {
                pubkey: kani::any(),
            },
            escrow: KaniAccount {
                pubkey: kani::any(),
            },
            escrow_ta: KaniAccount {
                pubkey: kani::any(),
            },
            initializer_ta: KaniAccount {
                pubkey: kani::any(),
            },
            token_program: KaniAccount {
                pubkey: kani::any(),
            },
        };
        kani::cover!(
            cancel(&mut s, &accounts_1),
            "cancel_path trace is reachable"
        );
    }
}

// ============================================================================
// Liveness properties — bounded reachability via non-deterministic ops
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_liveness_escrow_settles() {
    let mut s = State {
        initializer: kani::any(),
        initializer_token_account: kani::any(),
        taker: kani::any(),
        initializer_amount: kani::any(),
        taker_amount: kani::any(),
        escrow_token_account: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Open);
    for _ in 0..1 {
        let op: u8 = kani::any();
        match op {
            0 => {
                let accounts = ExchangeAccounts {
                    taker: KaniAccount {
                        pubkey: kani::any(),
                    },
                    escrow: KaniAccount {
                        pubkey: kani::any(),
                    },
                    initializer_ta: KaniAccount {
                        pubkey: kani::any(),
                    },
                    taker_ta: KaniAccount {
                        pubkey: kani::any(),
                    },
                    escrow_ta: KaniAccount {
                        pubkey: kani::any(),
                    },
                    token_program: KaniAccount {
                        pubkey: kani::any(),
                    },
                };
                exchange(&mut s, &accounts);
            }
            1 => {
                let accounts = CancelAccounts {
                    initializer: KaniAccount {
                        pubkey: kani::any(),
                    },
                    escrow: KaniAccount {
                        pubkey: kani::any(),
                    },
                    escrow_ta: KaniAccount {
                        pubkey: kani::any(),
                    },
                    initializer_ta: KaniAccount {
                        pubkey: kani::any(),
                    },
                    token_program: KaniAccount {
                        pubkey: kani::any(),
                    },
                };
                cancel(&mut s, &accounts);
            }
            _ => {}
        }
    }
    kani::cover!(
        s.status == Status::Closed,
        "escrow_settles reaches Closed within 1 steps"
    );
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
