// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:05f38e09fee2e6f9
use quasar_lang::prelude::*;
use crate::state::*;
use crate::events::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct Cancel {
    #[account(mut)]
    pub initializer: Signer,
    #[account(mut, seeds = EscrowAccount::seeds(escrow), bump)]
    pub escrow: Account<()>,
    #[account(mut, token::authority = escrow)]
    pub escrow_ta: Account<Token>,
    #[account(mut)]
    pub initializer_ta: Account<Token>,
    pub token_program: Program<()>,
}

impl Cancel {
    /// Initializer reclaims their deposit and closes the escrow
    #[inline(always)]
    pub fn handler(&mut self, bumps: &CancelBumps) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec: emit!(EscrowCancelled)
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
