// ---- GENERATED BY QEDGEN — DO NOT EDIT — regenerated from .qedspec ----
//! Per-handler guard checks derived from the `.qedspec`.
//! Called from user-owned `instructions/<name>::handler` before
//! business logic; keep guard logic here, policy-free logic there.

#![allow(
    unused_variables,
    unused_imports,
    dead_code,
    clippy::too_many_arguments
)]

use crate::errors::*;
use crate::state::*;
use crate::*;
use anchor_lang::prelude::*;

/// Guards for `initialize`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn initialize<'info>(ctx: &mut Initialize<'info>) -> Result<()> {
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `deposit`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn deposit<'info>(ctx: &mut Deposit<'info>, amount: u64) -> Result<()> {
    // lifecycle: require inner == Active
    if !matches!(ctx.vault.inner, VaultAccountInner::Active { .. }) {
        return Err(crate::errors::VaultError::InvalidLifecycle.into());
    }
    // requires: amount > 0
    if !(amount > 0) {
        return Err(VaultError::InvalidAmount.into());
    }
    Ok(())
}

/// Guards for `emergency_close`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn emergency_close<'info>(ctx: &mut EmergencyClose<'info>) -> Result<()> {
    // lifecycle: require inner == Active
    if !matches!(ctx.vault.inner, VaultAccountInner::Active { .. }) {
        return Err(crate::errors::VaultError::InvalidLifecycle.into());
    }
    // requires: admin_config.admin = admin.pubkey
    if !(ctx.admin_config.admin == ctx.admin.key()) {
        return Err(VaultError::Unauthorized.into());
    }
    Ok(())
}

// ---- END GENERATED ----
