// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:f14e30192758cfbd
// QuasarSVM integration test scaffold.
// Tests run against the compiled .so binary via quasar-svm.
//
// AGENT: fill instruction builder data and assertions marked with todo!().
//
// Prerequisites:
//   1. Build your program: cargo build-sbf (or cargo build --target bpfel-unknown-none)
//   2. Run tests: cargo test --features client
//
// Dev-dependencies (add to Cargo.toml):
//   [dev-dependencies]
//   escrow-client = { path = "client" }
//   quasar-svm = { git = "https://github.com/blueshift-gg/quasar-svm" }

extern crate std;
use {
    alloc::vec,
    escrow_client::*,
    quasar_svm::{Account, Instruction, Pubkey, QuasarSvm},
    spl_token_interface::state::{Account as TokenAccount, AccountState, Mint},
    std::{println, vec},
};

// ── Setup ────────────────────────────────────────────────────────

fn setup() -> QuasarSvm {
    let elf = std::fs::read("../../target/deploy/escrow.so").unwrap();
    QuasarSvm::new()
        .with_program(&crate::ID, &elf)
        .with_token_program()
}

// ── Account helpers ──────────────────────────────────────────────

fn signer(address: Pubkey) -> Account {
    quasar_svm::token::create_keyed_system_account(&address, 10_000_000_000)
}

fn empty(address: Pubkey) -> Account {
    Account {
        address,
        lamports: 0,
        data: vec![],
        owner: quasar_svm::system_program::ID,
        executable: false,
    }
}

/// Create a pre-populated EscrowAccount account (program-owned).
fn state_account(
    address: Pubkey,
    initializer: [u8; 32],
    initializer_token_account: [u8; 32],
    taker: [u8; 32],
    initializer_amount: u64,
    taker_amount: u64,
    escrow_token_account: [u8; 32],
    bump: u8,
) -> Account {
    let state = EscrowAccount {
        initializer,
        initializer_token_account,
        taker,
        initializer_amount,
        taker_amount,
        escrow_token_account,
        bump,
    };
    Account {
        address,
        lamports: 2_000_000,
        data: wincode::serialize(&state).unwrap(),
        owner: crate::ID,
        executable: false,
    }
}

fn mint_account(address: Pubkey, authority: Pubkey) -> Account {
    quasar_svm::token::create_keyed_mint_account(
        &address,
        &Mint {
            mint_authority: Some(authority).into(),
            supply: 1_000_000_000,
            decimals: 9,
            is_initialized: true,
            freeze_authority: None.into(),
        },
    )
}

fn token_account(address: Pubkey, mint: Pubkey, owner: Pubkey, amount: u64) -> Account {
    quasar_svm::token::create_keyed_token_account(
        &address,
        &TokenAccount {
            mint,
            owner,
            amount,
            state: AccountState::Initialized,
            ..TokenAccount::default()
        },
    )
}

// ── initialize ──

#[test]
fn test_initialize() {
    let mut svm = setup();

    // Account addresses
    let system_program = quasar_svm::system_program::ID;
    let rent = quasar_svm::solana_sdk_ids::sysvar::rent::ID;
    let initializer = Pubkey::new_unique();
    let (escrow, _escrow_bump) = Pubkey::find_program_address(
        &[b"escrow", initializer.as_ref()],
        &crate::ID,
    );
    let mint = Pubkey::new_unique();
    let initializer_ta = Pubkey::new_unique();
    let escrow_ta = Pubkey::new_unique();

    // Instruction parameters
    let deposit_amount: u64 = 1_000_000; // AGENT: set appropriate value
    let receive_amount: u64 = 1_000_000; // AGENT: set appropriate value

    let instruction: Instruction = InitializeInstruction {
        initializer,
        escrow,
        mint,
        initializer_ta,
        escrow_ta,
        token_program,
        system_program,
        deposit_amount,
        receive_amount,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(initializer),
            empty(escrow),
            empty(mint),
            token_account(initializer_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
            token_account(escrow_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
        ],
    );

    assert!(result.is_ok(), "initialize failed: {:?}", result.raw_result);

    // AGENT: verify account state after instruction
    // let escrow_data = &result.account(&escrow).unwrap().data;
    // let initializer_ta_data = &result.account(&initializer_ta).unwrap().data;
    // let escrow_ta_data = &result.account(&escrow_ta).unwrap().data;
    // Spec effect: initializer_amount set deposit_amount
    // Spec effect: taker_amount set receive_amount
    // Spec effect: initializer_token_account set initializer_ta.pubkey

    println!("  INITIALIZE CU: {}", result.compute_units_consumed);
}

// ── exchange ──

#[test]
fn test_exchange() {
    let mut svm = setup();

    // Account addresses
    let taker = Pubkey::new_unique();
    let (escrow, _escrow_bump) = Pubkey::find_program_address(
        &[b"escrow", initializer.as_ref()],
        &crate::ID,
    );
    let initializer_ta = Pubkey::new_unique();
    let taker_ta = Pubkey::new_unique();
    let escrow_ta = Pubkey::new_unique();

    let instruction: Instruction = ExchangeInstruction {
        taker,
        escrow,
        initializer_ta,
        taker_ta,
        escrow_ta,
        token_program,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(taker),
            empty(escrow) /* AGENT: use state_account() with appropriate fields */,
            token_account(initializer_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
            token_account(taker_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
            token_account(escrow_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
        ],
    );

    assert!(result.is_ok(), "exchange failed: {:?}", result.raw_result);

    println!("  EXCHANGE CU: {}", result.compute_units_consumed);
}

// ── cancel ──

#[test]
fn test_cancel() {
    let mut svm = setup();

    // Account addresses
    let initializer = Pubkey::new_unique();
    let (escrow, _escrow_bump) = Pubkey::find_program_address(
        &[b"escrow", initializer.as_ref()],
        &crate::ID,
    );
    let escrow_ta = Pubkey::new_unique();
    let initializer_ta = Pubkey::new_unique();

    let instruction: Instruction = CancelInstruction {
        initializer,
        escrow,
        escrow_ta,
        initializer_ta,
        token_program,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(initializer),
            empty(escrow) /* AGENT: use state_account() with appropriate fields */,
            token_account(escrow_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
            token_account(initializer_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
        ],
    );

    assert!(result.is_ok(), "cancel failed: {:?}", result.raw_result);

    println!("  CANCEL CU: {}", result.compute_units_consumed);
}

/// initialize must reject unauthorized callers (wrong initializer).
#[test]
fn test_initialize_unauthorized() {
    let mut svm = setup();

    let system_program = quasar_svm::system_program::ID;
    let rent = quasar_svm::solana_sdk_ids::sysvar::rent::ID;
    let wrong_initializer = Pubkey::new_unique();
    let escrow = Pubkey::new_unique();
    let mint = Pubkey::new_unique();
    let initializer_ta = Pubkey::new_unique();
    let escrow_ta = Pubkey::new_unique();

    let instruction: Instruction = InitializeInstruction {
        initializer: wrong_initializer,
        escrow,
        mint,
        initializer_ta,
        escrow_ta,
        token_program,
        system_program,
        deposit_amount: 1_000_000,
        receive_amount: 1_000_000,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(wrong_initializer),
            empty(escrow),
            empty(mint),
            token_account(initializer_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
            token_account(escrow_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
        ],
    );

    assert!(result.is_err(), "initialize should reject wrong initializer");
}

/// exchange must reject unauthorized callers (wrong taker).
#[test]
fn test_exchange_unauthorized() {
    let mut svm = setup();

    let wrong_taker = Pubkey::new_unique();
    let escrow = Pubkey::new_unique();
    let initializer_ta = Pubkey::new_unique();
    let taker_ta = Pubkey::new_unique();
    let escrow_ta = Pubkey::new_unique();

    let instruction: Instruction = ExchangeInstruction {
        taker: wrong_taker,
        escrow,
        initializer_ta,
        taker_ta,
        escrow_ta,
        token_program,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(wrong_taker),
            empty(escrow) /* AGENT: use state_account() with appropriate fields */,
            token_account(initializer_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
            token_account(taker_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
            token_account(escrow_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
        ],
    );

    assert!(result.is_err(), "exchange should reject wrong taker");
}

/// cancel must reject unauthorized callers (wrong initializer).
#[test]
fn test_cancel_unauthorized() {
    let mut svm = setup();

    let wrong_initializer = Pubkey::new_unique();
    let escrow = Pubkey::new_unique();
    let escrow_ta = Pubkey::new_unique();
    let initializer_ta = Pubkey::new_unique();

    let instruction: Instruction = CancelInstruction {
        initializer: wrong_initializer,
        escrow,
        escrow_ta,
        initializer_ta,
        token_program,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(wrong_initializer),
            empty(escrow) /* AGENT: use state_account() with appropriate fields */,
            token_account(escrow_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
            token_account(initializer_ta, Pubkey::new_unique(), Pubkey::new_unique(), 1_000_000) /* AGENT: set mint, owner, amount */,
        ],
    );

    assert!(result.is_err(), "cancel should reject wrong initializer");
}

// ── Lifecycle sequence ────────────────────────────────────────────

/// End-to-end lifecycle: execute operations in spec order.
/// AGENT: fill in instruction parameters and account setup for each step.
#[test]
fn test_lifecycle_sequence() {
    let mut svm = setup();

    // Lifecycle transitions:
    //   initialize : Uninitialized → Open
    //   exchange : Open → Closed
    //   cancel : Open → Closed

    // Step 1: initialize (Uninitialized → Open)
    // AGENT: build and execute initialize instruction
    todo!("build instruction sequence");
}

