// ---- GENERATED BY QEDGEN ---- spec-hash:d25d7c10b16e32df
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

mod pool {
    use super::*;

#[derive(Clone, Copy, PartialEq, Eq, kani::Arbitrary)]
enum Status {
    Uninitialized,
    Active,
    Paused,
}

#[derive(Clone, Copy)]
struct State {
    authority: [u8; 32],
    total_deposits: u64,
    total_borrows: u64,
    interest_rate: u64,
    status: Status,
}

// ============================================================================
// Property predicates (from qedspec `property` declarations)
// ============================================================================

/// pool_solvency: s.total_deposits ≥ s.total_borrows
fn pool_solvency(s: &State) -> bool {
    s.total_deposits >= s.total_borrows
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn init_pool(s: &mut State, rate: u64) -> bool {
    if !((rate > 0)) {
        return false;
    }
    if s.status != Status::Uninitialized {
        return false;
    }
    s.interest_rate = rate;
    s.total_deposits = 0;
    s.total_borrows = 0;
    s.status = Status::Active;
    true
}

fn deposit(s: &mut State, amount: u64) -> bool {
    if !((amount > 0)) {
        return false;
    }
    if s.status != Status::Active {
        return false;
    }
    match s.total_deposits.checked_add(amount) {
        Some(__v) => s.total_deposits = __v,
        None => return false,
    }
    s.status = Status::Active;
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_init_pool_rejects_invalid() {
    let mut s = State {
        authority: kani::any(),
        total_deposits: kani::any(),
        total_borrows: kani::any(),
        interest_rate: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Uninitialized);
    let rate: u64 = kani::any();
    kani::assume(!((rate > 0)));
    assert!(!init_pool(&mut s, rate),
        "init_pool must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_rejects_invalid() {
    let mut s = State {
        authority: kani::any(),
        total_deposits: kani::any(),
        total_borrows: kani::any(),
        interest_rate: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    kani::assume(!((amount > 0)));
    assert!(!deposit(&mut s, amount),
        "deposit must reject when guard is violated");
}

// ============================================================================
// Property preservation — invariants hold through all transitions
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_init_pool_preserves_pool_solvency() {
    let mut s = State {
        authority: 0,
        total_deposits: 0,
        total_borrows: 0,
        interest_rate: 0,
        status: Status::Uninitialized,
    };
    let rate: u64 = kani::any();
    if init_pool(&mut s, rate) {
        assert!(pool_solvency(&s),
            "pool_solvency must hold after init_pool");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_preserves_pool_solvency() {
    let mut s = State {
        authority: kani::any(),
        total_deposits: kani::any(),
        total_borrows: kani::any(),
        interest_rate: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    kani::assume(pool_solvency(&s));
    let amount: u64 = kani::any();
    if deposit(&mut s, amount) {
        assert!(pool_solvency(&s),
            "pool_solvency must hold after deposit");
    }
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_init_pool_effect_interest_rate() {
    let mut s = State {
        authority: 0,
        total_deposits: 0,
        total_borrows: 0,
        interest_rate: 0,
        status: Status::Uninitialized,
    };
    let rate: u64 = kani::any();
    let pre_authority = s.authority;
    let pre_total_deposits = s.total_deposits;
    let pre_total_borrows = s.total_borrows;
    if init_pool(&mut s, rate) {
        assert!(s.interest_rate == rate, "interest_rate must equal rate");
        assert!(s.authority == pre_authority, "authority must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_init_pool_effect_total_deposits() {
    let mut s = State {
        authority: 0,
        total_deposits: 0,
        total_borrows: 0,
        interest_rate: 0,
        status: Status::Uninitialized,
    };
    let rate: u64 = kani::any();
    let pre_authority = s.authority;
    let pre_total_borrows = s.total_borrows;
    let pre_interest_rate = s.interest_rate;
    if init_pool(&mut s, rate) {
        assert!(s.total_deposits == 0, "total_deposits must equal 0");
        assert!(s.authority == pre_authority, "authority must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_init_pool_effect_total_borrows() {
    let mut s = State {
        authority: 0,
        total_deposits: 0,
        total_borrows: 0,
        interest_rate: 0,
        status: Status::Uninitialized,
    };
    let rate: u64 = kani::any();
    let pre_authority = s.authority;
    let pre_total_deposits = s.total_deposits;
    let pre_interest_rate = s.interest_rate;
    if init_pool(&mut s, rate) {
        assert!(s.total_borrows == 0, "total_borrows must equal 0");
        assert!(s.authority == pre_authority, "authority must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_effect_total_deposits() {
    let mut s = State {
        authority: kani::any(),
        total_deposits: kani::any(),
        total_borrows: kani::any(),
        interest_rate: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    let pre_authority = s.authority;
    let pre_total_deposits = s.total_deposits;
    let pre_total_borrows = s.total_borrows;
    let pre_interest_rate = s.interest_rate;
    if deposit(&mut s, amount) {
        assert!(s.total_deposits == pre_total_deposits.wrapping_add(amount), "total_deposits must increment by amount");
        assert!(s.authority == pre_authority, "authority must not change");
        assert!(s.total_borrows == pre_total_borrows, "total_borrows must not change");
        assert!(s.interest_rate == pre_interest_rate, "interest_rate must not change");
    }
}

// ============================================================================
// Overflow detection — Kani catches arithmetic overflow on add effects
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_no_overflow() {
    let mut s = State {
        authority: kani::any(),
        total_deposits: kani::any(),
        total_borrows: kani::any(),
        interest_rate: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    deposit(&mut s, amount);  // Kani detects overflow on += internally
}

} // mod pool

mod loan {
    use super::*;

#[derive(Clone, Copy, PartialEq, Eq, kani::Arbitrary)]
enum Status {
    Empty,
    Active,
    Liquidated,
}

#[derive(Clone, Copy)]
struct State {
    borrower: [u8; 32],
    pool: [u8; 32],
    amount: u64,
    collateral: u64,
    status: Status,
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn borrow(s: &mut State, amount: u64, collateral: u64) -> bool {
    if !(((amount > 0) && (collateral > 0))) {
        return false;
    }
    if s.status != Status::Empty {
        return false;
    }
    s.amount = amount;
    s.collateral = collateral;
    s.status = Status::Active;
    true
}

fn repay(s: &mut State) -> bool {
    if s.status != Status::Active {
        return false;
    }
    s.amount = 0;
    s.collateral = 0;
    s.status = Status::Empty;
    true
}

fn liquidate(s: &mut State) -> bool {
    if !((s.amount > s.collateral)) {
        return false;
    }
    if s.status != Status::Active {
        return false;
    }
    s.amount = 0;
    s.status = Status::Liquidated;
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_borrow_rejects_invalid() {
    let mut s = State {
        borrower: kani::any(),
        pool: kani::any(),
        amount: kani::any(),
        collateral: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Empty);
    let amount: u64 = kani::any();
    let collateral: u64 = kani::any();
    kani::assume(!(((amount > 0) && (collateral > 0))));
    assert!(!borrow(&mut s, amount, collateral),
        "borrow must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_liquidate_rejects_invalid() {
    let mut s = State {
        borrower: kani::any(),
        pool: kani::any(),
        amount: kani::any(),
        collateral: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    kani::assume(!((s.amount > s.collateral)));
    assert!(!liquidate(&mut s),
        "liquidate must reject when guard is violated");
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_borrow_effect_amount() {
    let mut s = State {
        borrower: kani::any(),
        pool: kani::any(),
        amount: kani::any(),
        collateral: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Empty);
    let amount: u64 = kani::any();
    let collateral: u64 = kani::any();
    let pre_borrower = s.borrower;
    let pre_pool = s.pool;
    let pre_collateral = s.collateral;
    if borrow(&mut s, amount, collateral) {
        assert!(s.amount == amount, "amount must equal amount");
        assert!(s.borrower == pre_borrower, "borrower must not change");
        assert!(s.pool == pre_pool, "pool must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_borrow_effect_collateral() {
    let mut s = State {
        borrower: kani::any(),
        pool: kani::any(),
        amount: kani::any(),
        collateral: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Empty);
    let amount: u64 = kani::any();
    let collateral: u64 = kani::any();
    let pre_borrower = s.borrower;
    let pre_pool = s.pool;
    let pre_amount = s.amount;
    if borrow(&mut s, amount, collateral) {
        assert!(s.collateral == collateral, "collateral must equal collateral");
        assert!(s.borrower == pre_borrower, "borrower must not change");
        assert!(s.pool == pre_pool, "pool must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_repay_effect_amount() {
    let mut s = State {
        borrower: kani::any(),
        pool: kani::any(),
        amount: kani::any(),
        collateral: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let pre_borrower = s.borrower;
    let pre_pool = s.pool;
    let pre_collateral = s.collateral;
    if repay(&mut s) {
        assert!(s.amount == 0, "amount must equal 0");
        assert!(s.borrower == pre_borrower, "borrower must not change");
        assert!(s.pool == pre_pool, "pool must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_repay_effect_collateral() {
    let mut s = State {
        borrower: kani::any(),
        pool: kani::any(),
        amount: kani::any(),
        collateral: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let pre_borrower = s.borrower;
    let pre_pool = s.pool;
    let pre_amount = s.amount;
    if repay(&mut s) {
        assert!(s.collateral == 0, "collateral must equal 0");
        assert!(s.borrower == pre_borrower, "borrower must not change");
        assert!(s.pool == pre_pool, "pool must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_liquidate_effect_amount() {
    let mut s = State {
        borrower: kani::any(),
        pool: kani::any(),
        amount: kani::any(),
        collateral: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let pre_borrower = s.borrower;
    let pre_pool = s.pool;
    let pre_collateral = s.collateral;
    if liquidate(&mut s) {
        assert!(s.amount == 0, "amount must equal 0");
        assert!(s.borrower == pre_borrower, "borrower must not change");
        assert!(s.pool == pre_pool, "pool must not change");
        assert!(s.collateral == pre_collateral, "collateral must not change");
    }
}

} // mod loan

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
