// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:fc7b9cc9b879eba1
use quasar_lang::prelude::*;

#[error_code]
pub enum EscrowError {
    InvalidAmount = 0,
    Unauthorized = 1,
    AlreadyClosed = 2,
    InvalidLifecycle = 3,
    InvalidPda = 4,
}
// ---- END GENERATED ----
