// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:2ddc91614bef54d1
use quasar_lang::prelude::*;

#[event(discriminator = 1)]
pub struct EscrowInitialized {
    pub initializer: Pubkey,
    pub amount: u64,
}

#[event(discriminator = 2)]
pub struct EscrowExchanged {
    pub taker: Pubkey,
    pub amount: u64,
}

#[event(discriminator = 3)]
pub struct EscrowCancelled {
    pub initializer: Pubkey,
}

// ---- END GENERATED ----
