// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:382fd5d9b1996d0e
#![allow(unexpected_cfgs)]
#![cfg_attr(any(target_os = "solana", target_arch = "bpf"), no_std)]

use quasar_lang::prelude::*;

mod instructions;
use instructions::*;
pub mod events;
pub mod errors;
pub mod state;
pub mod guards;

declare_id!("11111111111111111111111111111111");

#[program]
mod escrow {
    use super::*;

    #[instruction(discriminator = 0)]
    pub fn initialize(ctx: Ctx<Initialize>, deposit_amount: u64, receive_amount: u64) -> Result<(), ProgramError> {
        ctx.accounts.handler(deposit_amount, receive_amount, &ctx.bumps)
    }

    #[instruction(discriminator = 1)]
    pub fn exchange(ctx: Ctx<Exchange>) -> Result<(), ProgramError> {
        ctx.accounts.handler(&ctx.bumps)
    }

    #[instruction(discriminator = 2)]
    pub fn cancel(ctx: Ctx<Cancel>) -> Result<(), ProgramError> {
        ctx.accounts.handler(&ctx.bumps)
    }

}
// ---- END GENERATED ----
