// Single source of truth for the "GENERATED BY QEDGEN" banner — downstream
// tooling (drift detection, fill markers) parses the exact punctuation and
// hash placement, so every emitter must go through here.

pub fn banner(label: Option<&str>, hash: &str) -> String {
    let has_hash = !hash.is_empty();
    match (label, has_hash) {
        (Some(l), true) => format!(
            "// ---- GENERATED BY QEDGEN — {} ---- spec-hash:{}\n",
            l, hash
        ),
        (Some(l), false) => format!("// ---- GENERATED BY QEDGEN — {} ----\n", l),
        (None, true) => format!("// ---- GENERATED BY QEDGEN ---- spec-hash:{}\n", hash),
        (None, false) => "// ---- GENERATED BY QEDGEN ----\n".to_string(),
    }
}
