//! Reproducer harness generation (#228).
//!
//! `qedgen probe` predicates flag *candidate* issues; a candidate becomes a
//! *finding* only when a concrete reproducer confirms it. This module
//! mechanically generates those reproducers from the spec — deterministic
//! translation, same class of work as `codegen --proptest`, so it lives in
//! codegen (never business logic).
//!
//! The first category wired end-to-end is `ArithmeticOverflowWrapping`. Its
//! reproducer is a self-contained Rust program that models the spec effect's
//! wrapping operator (`+=?` / `-=?`) and drives its operands to the overflow
//! boundary: the witness is closed-form (no search), so the harness is a
//! deterministic *boundary-value* demonstration rather than a proptest seed.
//! It exits 0 iff the wrap reproduces — a checked op would have rejected the
//! same input — so a build-and-run either confirms the finding or doesn't.
//!
//! Generation is pure and side-effect-free (returns source text); writing and
//! optionally executing the harness is the probe layer's job.

/// A generated reproducer: Rust source plus a human description of the exact
/// input it pins.
#[derive(Debug, Clone)]
pub struct GeneratedRepro {
    /// Complete, self-contained Rust source (`fn main()` with asserts).
    pub source: String,
    /// The concrete failing input the harness drives, for human inspection
    /// and to persist alongside the finding.
    pub failing_input: String,
}

/// Map a DSL integer type (`U8`..`U128`) to its Rust type. Returns `None` for
/// non-integer or unknown field types — the caller then can't build a
/// boundary reproducer and keeps the hit as an un-harnessed candidate.
pub fn rust_int_type(dsl_ty: &str) -> Option<&'static str> {
    match dsl_ty.trim() {
        "U8" => Some("u8"),
        "U16" => Some("u16"),
        "U32" => Some("u32"),
        "U64" => Some("u64"),
        "U128" => Some("u128"),
        _ => None,
    }
}

/// Generate the boundary-value reproducer for a wrapping arithmetic effect.
///
/// - `op` is the effect op string: `add_wrap` or `sub_wrap` (the checked /
///   saturating ops don't reach here — they aren't the vulnerability).
/// - `rust_ty` is the field's Rust integer type (`u64`, …) from
///   [`rust_int_type`].
///
/// Returns `None` for a non-wrapping op (defensive; the caller only routes
/// wrapping hits here).
pub fn arith_overflow_boundary(
    handler: &str,
    field: &str,
    op: &str,
    operand_desc: &str,
    rust_ty: &str,
) -> Option<GeneratedRepro> {
    // Boundary witnesses: the minimal concrete input that makes the wrapping
    // operator differ observably from the checked default.
    //   add_wrap: field = 1,           operand = TYPE::MAX  → wraps to 0
    //   sub_wrap: field = 0,           operand = 1          → wraps to MAX
    let (pre, operand, method, checked, saturating, failing_input) = match op {
        "add_wrap" => (
            "1".to_string(),
            format!("{rust_ty}::MAX"),
            "wrapping_add",
            "checked_add",
            "saturating_add",
            format!("{field} = 1, operand = {rust_ty}::MAX"),
        ),
        "sub_wrap" => (
            "0".to_string(),
            "1".to_string(),
            "wrapping_sub",
            "checked_sub",
            "saturating_sub",
            format!("{field} = 0, operand = 1"),
        ),
        _ => return None,
    };

    let sym = if method == "wrapping_add" {
        "+=?"
    } else {
        "-=?"
    };
    let source = format!(
        r#"// GENERATED by `qedgen probe` (#228) — reproducer for
// ArithmeticOverflowWrapping in handler `{handler}`.
//
// Spec effect: `{field} {sym} {operand_desc}` (wrapping — DSL `{sym}`).
// This boundary witness drives the operands so the wrapping operator
// silently overflows where the checked default (`+=` / `-=`) would abort.
// Exits 0 iff the wrap reproduces.

fn main() {{
    let field: {rust_ty} = {pre};
    let operand: {rust_ty} = {operand};

    // The spec's wrapping operator, as written:
    let wrapped = field.{method}(operand);

    // The checked default would have rejected this exact input:
    assert!(
        field.{checked}(operand).is_none(),
        "input is within checked range — not a reproduction of the wrap"
    );
    // ...and the wrap silently produced a different value than the clamped
    // (saturating) result would have — i.e. it overflowed. `saturating_*` is
    // used for the comparison because it is total (unlike raw math, which
    // would itself overflow at this boundary).
    assert_ne!(
        wrapped,
        field.{saturating}(operand),
        "no wrap occurred — operator did not overflow"
    );

    eprintln!(
        "REPRODUCED: `{field} {sym} operand` silently wrapped to {{}} (checked would abort)",
        wrapped
    );
}}
"#,
    );

    Some(GeneratedRepro {
        source,
        failing_input,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_dsl_int_types() {
        assert_eq!(rust_int_type("U64"), Some("u64"));
        assert_eq!(rust_int_type("U128"), Some("u128"));
        assert_eq!(rust_int_type(" U8 "), Some("u8"));
        assert_eq!(rust_int_type("Pubkey"), None);
        assert_eq!(rust_int_type("Bool"), None);
    }

    #[test]
    fn add_wrap_boundary_drives_operand_to_max() {
        let r = arith_overflow_boundary("deposit", "balance", "add_wrap", "amount", "u64").unwrap();
        assert!(r.source.contains("let field: u64 = 1;"));
        assert!(r.source.contains("let operand: u64 = u64::MAX;"));
        assert!(r.source.contains("wrapping_add"));
        assert!(r.source.contains("checked_add"));
        assert!(r.failing_input.contains("u64::MAX"));
    }

    #[test]
    fn sub_wrap_boundary_underflows_from_zero() {
        let r =
            arith_overflow_boundary("withdraw", "balance", "sub_wrap", "amount", "u64").unwrap();
        assert!(r.source.contains("let field: u64 = 0;"));
        assert!(r.source.contains("let operand: u64 = 1;"));
        assert!(r.source.contains("wrapping_sub"));
        assert!(r.source.contains("checked_sub"));
    }

    #[test]
    fn non_wrapping_op_is_none() {
        assert!(arith_overflow_boundary("h", "f", "add", "x", "u64").is_none());
        assert!(arith_overflow_boundary("h", "f", "add_sat", "x", "u64").is_none());
    }

    /// The generated program must be self-contained (no external deps, has a
    /// `fn main`) so `rustc <file>` compiles it directly.
    #[test]
    fn generated_source_is_self_contained() {
        let r = arith_overflow_boundary("h", "f", "add_wrap", "x", "u128").unwrap();
        assert!(r.source.contains("fn main()"));
        assert!(
            !r.source.lines().any(|l| l.trim_start().starts_with("use ")),
            "must not depend on external crates (no `use` imports)"
        );
        assert!(r.source.contains("u128::MAX"));
        assert!(r.source.contains("saturating_add"));
    }
}
